// RUN; not %target-swift-frontend -experimental-skip-all-function-bodies -dump-parse %s | %FileCheck %s

// rdar://129195380 - Make sure the skipping logic can handle #if.
struct S {
  // CHECK: func_decl{{.*}}:[[@LINE+1]]:3 - line:[[@LINE+11]]:3{{.*}}"foo()"
  func foo() {
#if true
  }
#if true
  func bar() {
#else
  }
#endif
  }
#endif
  }
  // CHECK: func_decl{{.*}}:[[@LINE+1]]:3 - line:[[@LINE+1]]:15{{.*}}"baz()"
  func baz() {}
}

// The '#if' is unterminated here, so swallows the rest of the file.
// CHECK: struct_decl{{.*}}:[[@LINE+1]]:1 - line:[[@LINE+14]]:14{{.*}}"R"
struct R {
#if false
  }
#if true
  }
#endif
  }
#else
  }
  // CHECK-NOT: qux
  func qux() {}
}

func flim() {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/rdar129195380.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@8:3 {{}} // unexpected_rbrace_in_conditional_compilation_block
// expected-note@23:10 {{}} // opening_brace
// expected-error@25:3 {{}} // unexpected_rbrace_in_conditional_compilation_block
// expected-error@31:3 {{}} // unexpected_rbrace_in_conditional_compilation_block
// expected-error@49:1 2 {{}} // expected_close_to_if_directive,expected_rbrace_struct
// ---- end ASTGen parity ----
