// RUN; %target-typecheck-verify-swift -D FOO -D BAZ -swift-version 4

#if FOO == BAZ // expected_error{{expected '&&' or '||' expression}}
var x = 0
#endif

#if ^FOO // expected_error {{expected unary '!' expression}}
var y = 0
#endif

#if foo(BAR) // expected_error {{invalid conditional compilation expression}}
var z = 0
#endif

#if FOO || !FOO
func f() {}
#endif ; f() // expected_error {{extra tokens following conditional compilation directive}}

#if FOO || !FOO
func g() {}
#else g()  // expected_error {{extra tokens following conditional compilation directive}}
#endif


#if FOO || !FOO
func h() {}
#else /* aaa */
#endif /* bbb */

#if foo.bar() // expected_error {{invalid conditional compilation expression}}
      .baz()

#endif


// <https://twitter.com/practicalswift/status/829066902869786625>
#if // expected_error {{incomplete condition in conditional compilation directive}}
#if 0 == // expected_error {{incomplete condition in conditional compilation directive}}
#if 0= // expected_error {{incomplete condition in conditional compilation directive}} expected_error {{'=' must have consistent whitespace on both sides}}
class Foo {
  #if // expected_error {{incomplete condition in conditional compilation directive}}
  #if 0 == // expected_error {{incomplete condition in conditional compilation directive}}
  #if 0= // expected_error {{incomplete condition in conditional compilation directive}} expected_error {{'=' must have consistent whitespace on both sides}}
}

struct S {
  #if FOO
  #else
  #else  // expected_error {{further conditions after #else are unreachable}}
  #endif
  
  #if FOO
  #elseif BAR
  #elseif BAZ
  #else
  #endif
}

#if FOO
#else
#else  // expected_error {{further conditions after #else are unreachable}}
#endif

#if FOO
#elseif BAR
#elseif BAZ
#else
#endif

#if os(ios)
#endif

#if os(uOS)
#endif

#if os(xxxxxxd)
#endif

#if os(bisionos)

#endif

#if os(Firmware)
#endif

#if arch(arn)
#endif

#if _endian(mid) // expected_warning {{unknown endianness for build configuration '_endian'}}
#endif

LABEL: #if true // expected_error {{expected statement}}
func fn_i() {}
#endif
fn_i() // OK

try #if false // expected_error {{expected expression}}
#else
func fn_j() {}
#endif
fn_j() // OK

#if foo || bar || nonExistent() // expected_error {{invalid conditional compilation expression}}
#endif

#if FOO = false
// expected_error @-1 {{invalid conditional compilation expression}}
undefinedFunc() // ignored.
#else
undefinedFunc() // expected_error {{cannot find 'undefinedFunc' in scope}}
#endif

#if false
#elseif FOO ? true : false
// expected_error @-1 {{invalid conditional compilation expression}}
undefinedFunc() // ignored.
#else
undefinedFunc() // expected_error {{cannot find 'undefinedFunc' in scope}}
#endif

/// Invalid platform condition arguments don't invalidate the whole condition.
// expected_warning@+1{{unknown endianness}}
#if !arch(arn) && !os(ystem) && !_endian(ness)
func fn_k() {}
#endif
fn_k()

#if os(cillator) || arch(i3rm)
func undefinedFunc() // ignored.
#endif
undefinedFunc() // expected_error {{cannot find 'undefinedFunc' in scope}}

#if os(simulator)
#endif

#if arch(iOS)
#endif

#if _endian(arm64) // expected_warning {{unknown endianness for build configuration '_endian'}}
#endif

#if targetEnvironment(_ObjC)
#endif

#if os(iOS) || os(simulator)
#endif

#if arch(ios)
#endif

#if FOO
#else if BAR
// expected_error@-1 {{unexpected 'if' keyword following '#else' conditional compilation directive; did you mean '#elseif'?}} {{1-9=#elseif}}
#else
#endif

#if FOO
#else
if true {}
#endif // OK

// rdar://83017601 Make sure we don't crash
#if canImport()
// expected_error@-1 {{'canImport' requires a module name}}
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/basicParseErrors.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -D FOO -D BAZ -swift-version 4 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@3:9 {{}} // bridged_error
// expected-error@17:8 {{}} // extra_tokens_conditional_compilation_directive
// expected-error@21:7 {{}} // extra_tokens_conditional_compilation_directive
// expected-error@37:4 {{}} // incomplete_conditional_compilation_directive
// expected-error@38:9 {{}} // incomplete_conditional_compilation_directive
// expected-error@39:6 {{}} // lex_unary_equal
// expected-error@39:7 {{}} // incomplete_conditional_compilation_directive
// expected-error@41:6 {{}} // incomplete_conditional_compilation_directive
// expected-error@42:11 {{}} // incomplete_conditional_compilation_directive
// expected-error@43:8 {{}} // lex_unary_equal
// expected-error@43:9 {{}} // incomplete_conditional_compilation_directive
// expected-error@49:3 {{}} // expected_close_after_else_directive
// expected-error@61:1 {{}} // expected_close_after_else_directive
// expected-error@92:8 {{}} // expected_stmt
// expected-error@97:5 {{}} // expected_expr
// expected-error@152:7 {{}} // unexpected_if_following_else_compilation_directive
// ---- end ASTGen parity ----
