// RUN; %empty-directory(%t)
// RUN; %empty-directory(%t/textual)
// RUN; %empty-directory(%t/binary)

// RUN; echo "public func foo() {}" > %t/Foo.swift

// RUN; %target-swift-frontend -emit-module %t/Foo.swift -module-name NoUserModuleVersion -swift-version 5 -disable-implicit-concurrency-module-import -emit-module-interface-path %t/textual/NoUserModuleVersion.swiftinterface -enable-library-evolution -emit-module-path %t/binary/NoUserModuleVersion.swiftmodule

// RUN; %target-typecheck-verify-swift -disable-implicit-concurrency-module-import -I %t/textual
// RUN; %target-typecheck-verify-swift -disable-implicit-concurrency-module-import -I %t/binary

import NoUserModuleVersion

func testCanImportNoUserModuleVersion() {

#if canImport(NoUserModuleVersion, _version: 113.331) // expected_warning {{cannot find user version number for module 'NoUserModuleVersion'; version number ignored}}
  let a = 1 // expected_warning {{initialization of immutable value 'a' was never used; consider replacing with assignment to '_' or removing it}}
#endif

#if canImport(NoUserModuleVersion, _version: 2) // expected_warning {{cannot find user version number for module 'NoUserModuleVersion'; version number ignored}}
  let b = 1 // expected_warning {{initialization of immutable value 'b' was never used; consider replacing with assignment to '_' or removing it}}
#endif

}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/can_import_version_missing_user_module_version.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -disable-implicit-concurrency-module-import %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// ---- end ASTGen parity ----
