// RUN; %target-typecheck-verify-swift
// RUN; %target-typecheck-verify-swift -swift-version 4

#if !compiler(>=4.1)
 // There should be no error here.
 foo bar
#else
 let _: Int = 1
#endif

#if compiler(<4.1)
 // There should be no error here.
 foo bar
#else
 let _: Int = 1
#endif

#if (compiler(>=4.1))
 let _: Int = 1
#else
 // There should be no error here.
 foo bar
#endif

#if !compiler(<4.1)
 let _: Int = 1
#else
 // There should be no error here.
 foo bar
#endif

#if compiler(>=4.1)
 let _: Int = 1
#else
 #if false
  // There should be no error here.
  foo bar
 #endif
#endif

#if false
 #if compiler(>=4.1)
  let _: Int = 1
 #else
  // There should be no error here.
  foo bar
 #endif
#endif

#if compiler(>=4.1.0.0.0)
 let _: Int = 1
#else
 // There should be no error here.
 foo bar
#endif

#if compiler(>=4.1.0.0.0.0) // expected_warning {{trailing components of version '4.1.0.0.0' are ignored}}
 let _: Int = 1
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/compiler.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// ---- end ASTGen parity ----
