// RUN; %target-typecheck-verify-swift -swift-version 4

/// Reject compound names.
#if BAR(_:) // expected_error@:5 {{invalid conditional compilation expression}}
#elseif os(x:)(macOS) // expected_error@:9 {{invalid conditional compilation expression}}
#elseif os(Linux(foo:bar:)) // expected_error@:9 {{'os' requires a single unlabeled argument for the operating system}}
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/compoundName_swift4.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// ---- end ASTGen parity ----
