// RUN; %target-typecheck-verify-swift

class C2 { // expected_note {{to match this opening '{'}}
  #if FOO
  func foo() {}
// expected_error @+2 {{expected '}' in class}}
// expected_error @+1 {{expected #else or #endif at end of conditional compilation block}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/decl_parse_errors-2.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@3:10 {{}} // opening_brace
// expected-error@17:1 2 {{}} // expected_close_to_if_directive,expected_rbrace_class
// ---- end ASTGen parity ----
