// RUN; %target-typecheck-verify-swift

#if _runtime(_ObjC)
#endif

#if _runtime(_Native)
#endif

#if _runtime(ObjC) // expected_error{{unexpected argument for the '_runtime' condition; expected '_Native' or '_ObjC'}}
#endif

#if _runtime(Native) // expected_error{{unexpected argument for the '_runtime' condition; expected '_Native' or '_ObjC'}}
#endif

#if _runtime(Invalid) // expected_error{{unexpected argument for the '_runtime' condition; expected '_Native' or '_ObjC'}}
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/invalid-runtime-name.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// ---- end ASTGen parity ----
