// RUN; %swift -swift-version 4 -typecheck %s -verify -target %target-cpu-apple-ios12.0-macabi -parse-stdlib
// RUN; %swift-ide-test -swift-version 4 -test-input-complete -source-filename=%s -target %target-cpu-apple-ios12.0-macabi

// REQUIRES; OS=macosx || OS=maccatalyst

// expected_error@<unknown> {{invalid version number in '-target }}

#if targetEnvironment(macabi) // expected_warning {{'macabi' has been renamed to 'macCatalyst'}}
// expected_note@-1{{replace with 'macCatalyst'}}{{23-29=macCatalyst}}
func underMacABI() {
  foo() // expected_error {{cannot find 'foo' in scope}}
}
#endif

#if !targetEnvironment(macabi) // expected_warning {{'macabi' has been renamed to 'macCatalyst'}}
// expected_note@-1{{replace with 'macCatalyst'}}{{24-30=macCatalyst}}
// This block does not typecheck but the #if prevents it from
// from being a compiler error.
let i: SomeType = "SomeString" // no-error
#endif

#if targetEnvironment(macCatalyst)
func underTargetEnvironmentMacCatalyst() {
  foo() // expected_error {{cannot find 'foo' in scope}}
}
#endif

// Make sure we don't treat the macabi environment as a simulator.
#if targetEnvironment(simulator)
// This block does not typecheck but the #if prevents it from
// from being a compiler error.
let i: SomeType = "SomeString" // no-error
#endif

#if os(macCatalyst)
func underOSMacCatalyst() {
}
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/macabiTargetEnv.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 -target %target-cpu-apple-ios12.0-macabi -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: OS=macosx || OS=maccatalyst
// XFAIL: *
// expected-error@<unknown> {{}} // error_from_clang
// ---- end ASTGen parity ----
