// RUN; %target-typecheck-verify-swift

// With a space next to the '#if'
#if 
// expected_error@-1 {{incomplete condition in conditional compilation directive}}
class C {}
#endif  // expected_error {{unexpected conditional compilation block terminator}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/no_configuration_error1.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:4 {{}} // incomplete_conditional_compilation_directive
// expected-error@7:1 {{}} // unexpected_conditional_compilation_block_terminator
// ---- end ASTGen parity ----
