// RUN; %target-typecheck-verify-swift -D BLAH

// Check that if config statement has range properly nested in its parent
// EOF.

func foo() { // expected_note {{to match this opening '{'}}
#if BLAH
#elseif !BLAH
// expected_error@+2{{expected '}' at end of brace statement}}
// expected_error@+1{{expected #else or #endif at end of conditional compilation block}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/pound-if-inside-function-2.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -D BLAH %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@6:12 {{}} // opening_brace
// expected-error@20:1 2 {{}} // expected_close_to_if_directive,expected_rbrace_in_brace_stmt
// ---- end ASTGen parity ----
