// RUN; %target-typecheck-verify-swift -D BLAH

// Check that if config statement has range properly nested in its parent
// EOF.

#if BLAH
// expected_error@+1{{expected #else or #endif at end of conditional compilation block}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/pound-if-top-level.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -D BLAH %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@16:1 {{}} // expected_close_to_if_directive
// ---- end ASTGen parity ----
