// RUN; %target-typecheck-verify-swift

#if arch(x86_64)
// expected_error@+2{{expected '{' in protocol type}}
// expected_error@+1{{extraneous '}' at top level}}
public protocol CS}
// expected_error@+1{{expected #else or #endif at end of conditional compilation block}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/pound-if-top-level-3.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@6:19 2 {{}} // expected_lbrace_protocol,extra_rbrace
// expected-error@17:1 {{}} // expected_close_to_if_directive
// ---- end ASTGen parity ----
