// RUN; %target-typecheck-verify-swift

#if 0  // expected_error {{'0' is not a valid conditional compilation expression, use 'false'}}
// expected_note@-1{{replace with Boolean literal 'false'}}{{5-6=false}}
  let x = 1
#endif

#if 1  // expected_error {{'1' is not a valid conditional compilation expression, use 'true'}}
// expected_note@-1{{replace with Boolean literal 'true'}}{{5-6=true}}
  let x = 1
#endif


// expected_error@+1{{invalid conditional compilation expression}}
#if 6
var u: V { didSet {} }

// expected_error@+1{{expected #else or #endif at end of conditional compilation block}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/pound-if-top-level-2.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@27:1 {{}} // expected_close_to_if_directive
// ---- end ASTGen parity ----
