// RUN; %target-typecheck-verify-swift -swift-version 4

#if false || true && false
undefinedIf()
#else
undefinedElse() // expected_error {{cannot find 'undefinedElse' in scope}}
#endif

#if false && true || true
undefinedIf() // expected_error {{cannot find 'undefinedIf' in scope}}
#else
undefinedElse()
#endif

#if false || true && false || false
undefinedIf()
#else
undefinedElse() // expected_error {{cannot find 'undefinedElse' in scope}}
#endif

// expected_error @+1 {{invalid conditional compilation expression}}
#if false || true && try! Swift
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/sequence.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// ---- end ASTGen parity ----
