// RUN; %target-typecheck-verify-swift -parse-as-library -D FOO

// '-parse-as-library' doesn't allow expressions nor statements in #if blocks.

func foo() {}

#if FOO
  foo() // expected_error {{expressions are not allowed at the top level}}
#else
  if true { foo() } // expected_error {{statements are not allowed at the top level}}
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/toplevel_parseaslibrary.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-as-library -D FOO %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@8:3 {{}} // illegal_top_level_expr
// expected-error@10:3 {{}} // illegal_top_level_stmt
// ---- end ASTGen parity ----
