// RUN; %target-typecheck-verify-swift

public
#if FOO // expected_error {{expected declaration}}
var val1: Int = 0
#else
var val1: UInt = 1
#endif

struct S2 { // expected_note {{in declaration of 'S2'}}
  @available(*, deprecated)
#if FOO // expected_error {{expected declaration}}
  func fn1() {}
#endif
}

// expected_error@+2 {{expected declaration}}
private
#sourceLocation(file: "test.swift", line: 1)
var val2: Int = 0
#sourceLocation()

// expected_error@+3 {{expected declaration}}
// expected_error@+2 {{#line directive was renamed to #sourceLocation}}
lazy
#line 12 "test.swift"
var val3: Int = 0;
#line // expected_error {{#line directive was renamed to #sourceLocation}}

class C { // expected_note {{to match this opening '{'}}

#if os(iOS)
	func foo() {}
} // expected_error{{unexpected '}' in conditional compilation block}}
#else
	func bar() {}
	func baz() {}
} // expected_error{{unexpected '}' in conditional compilation block}}
#endif
// expected_error@+1{{expected '}' in class}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/decl_parse_errors.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:1 {{}} // expected_decl
// expected-note@10:8 {{}} // note_in_decl_of
// expected-error@12:1 {{}} // expected_decl
// expected-error@19:1 {{}} // expected_decl
// expected-error@26:1 2 {{}} // expected_decl,line_directive_style_deprecated
// expected-error@28:1 {{}} // line_directive_style_deprecated
// expected-note@30:9 {{}} // opening_brace
// expected-error@34:1 {{}} // unexpected_rbrace_in_conditional_compilation_block
// expected-error@38:1 {{}} // unexpected_rbrace_in_conditional_compilation_block
// expected-error@58:1 {{}} // expected_rbrace_class
// ---- end ASTGen parity ----
