// RUN; %target-typecheck-verify-swift -D FOO

// Test case for statements in #if block in types.

func foo() {}

struct S1 { // expected_note {{in declaration of 'S1'}}
#if FOO
  return 1; // expected_error {{expected declaration}}
#elseif BAR
  foo(); // expected_error {{expected 'func' keyword in instance method declaration}}
#endif
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/stmt_in_type.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -D FOO %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@7:8 {{}} // note_in_decl_of
// expected-error@9:3 {{}} // expected_decl
// expected-error@11:3 {{}} // expected_keyword_in_decl
// ---- end ASTGen parity ----
