// RUN; %target-typecheck-verify-swift -parse -parse-stdlib

import Swift

@_alwaysEmitConformanceMetadata
protocol Test {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/alwaysEmitConformanceMetadata_attr.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
