// RUN; %target-typecheck-verify-swift -target %target-swift-5.1-abi-triple

// REQUIRES; concurrency

func asyncGlobal1() async { }
func asyncGlobal2() async throws { }

typealias AsyncFunc1 = () async -> ()
typealias AsyncFunc2 = () async throws -> ()
typealias AsyncFunc3 = (_ a: Bool, _ b: Bool) async throws -> ()

func testTypeExprs() {
  let _ = [() async -> ()]()
  let _ = [() async throws -> ()]()
}

func testAwaitOperator() async {
  let _ = await asyncGlobal1()
}

func testAsyncClosure() {
  let _ = { () async in 5 }
  let _ = { () throws in 5 }
  let _ = { () async throws in 5 }
}

func testAwait() async {
  let _ = await asyncGlobal1()
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/async-syntax.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -target %target-swift-5.1-abi-triple %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: concurrency
// parity: passing
// ---- end ASTGen parity ----
