// RUN; %target-typecheck-verify-swift -enable-experimental-move-only

var global: Int = 5
func testGlobal() {
    let _ = _borrow global
}

func testVar() {
    var t = String()
    t = String()
    let _ = _borrow t
}


// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/borrow_expr.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-move-only %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
