// RUN; %target-typecheck-verify-swift -parse-stdlib

precedencegroup AssignmentPrecedence { assignment: true }

var word: Builtin.Word
var i16: Builtin.Int16
var i32: Builtin.Int32
var i64: Builtin.Int64
var i128: Builtin.Int128

// Check that trunc/?ext operations are appropriately available given the
// abstract range of potential Word sizes.

word = Builtin.truncOrBitCast_Int128_Word(i128)
word = Builtin.truncOrBitCast_Int64_Word(i64)
word = Builtin.truncOrBitCast_Int32_Word(i32) // expected_error{{}}
word = Builtin.truncOrBitCast_Int16_Word(i16) // expected_error{{}}

i16 = Builtin.truncOrBitCast_Word_Int16(word)
i32 = Builtin.truncOrBitCast_Word_Int32(word)
i64 = Builtin.truncOrBitCast_Word_Int64(word) // expected_error{{}}
i128 = Builtin.truncOrBitCast_Word_Int128(word) // expected_error{{}}

word = Builtin.zextOrBitCast_Int128_Word(i128) // expected_error{{}}
word = Builtin.zextOrBitCast_Int64_Word(i64) // expected_error{{}}
word = Builtin.zextOrBitCast_Int32_Word(i32)
word = Builtin.zextOrBitCast_Int16_Word(i16)

i16 = Builtin.zextOrBitCast_Word_Int16(word) // expected_error{{}}
i32 = Builtin.zextOrBitCast_Word_Int32(word) // expected_error{{}}
i64 = Builtin.zextOrBitCast_Word_Int64(word)
i128 = Builtin.zextOrBitCast_Word_Int128(word)

word = Builtin.trunc_Int128_Word(i128)
word = Builtin.trunc_Int64_Word(i64) // expected_error{{}}
word = Builtin.trunc_Int32_Word(i32) // expected_error{{}}
word = Builtin.trunc_Int16_Word(i16) // expected_error{{}}

i16 = Builtin.trunc_Word_Int16(word)
i32 = Builtin.trunc_Word_Int32(word) // expected_error{{}}
i64 = Builtin.trunc_Word_Int64(word) // expected_error{{}}
i128 = Builtin.trunc_Word_Int128(word) // expected_error{{}}

word = Builtin.zext_Int128_Word(i128) // expected_error{{}}
word = Builtin.zext_Int64_Word(i64) // expected_error{{}}
word = Builtin.zext_Int32_Word(i32) // expected_error{{}}
word = Builtin.zext_Int16_Word(i16)

i16 = Builtin.zext_Word_Int16(word) // expected_error{{}}
i32 = Builtin.zext_Word_Int32(word) // expected_error{{}}
i64 = Builtin.zext_Word_Int64(word) // expected_error{{}}
i128 = Builtin.zext_Word_Int128(word)
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/builtin_word.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
