// RUN; %target-typecheck-verify-swift -parse-stdlib

precedencegroup AssignmentPrecedence { assignment: true }

var word: Builtin.Word

class C {}

var c: C
let bo = Builtin.castToBridgeObject(c, word)
c = Builtin.castReferenceFromBridgeObject(bo)
word = Builtin.castBitPatternFromBridgeObject(bo)
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/builtin_bridge_object.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
