// RUN; %target-typecheck-verify-swift -enable-experimental-feature CompileTimeValues
// REQUIRES; swift_feature_CompileTimeValues

@constInitialized let x: Int = 42
@constInitialized var y: Int = 42

protocol ConstUserProto {
	@constInitialized var v: String { get } // expected_error{{'@constInitialized' cannot be used inside a protocol declaration}}
}

class ConstFanClassWrong: ConstUserProto {
	@constInitialized var v: String = "" // expected_error{{properties with attribute @constInitialized must be static}}
  @constInitialized static var B: String = ""
  @constInitialized static var Computed: String { get { return "" } } // expected_error{{'@constInitialized' must not be used on computed properties}}
}

func takeIntConst(@constInitialized _ a: Int) {} // expected_error{{@constInitialized may only be used on 'var' declarations}}

@constInitialized func constFunc(_ a: Int) {} // expected_error{{@constInitialized may only be used on 'var' declarations}}

func LocalConstVarUser() -> Int {
		@constInitialized let localConst = 3 // expected_error{{attribute @constInitialized can only be used in a non-local scope}}
		return localConst + 1
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/constinitialized.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-feature CompileTimeValues %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_CompileTimeValues
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
