// RUN; %target-typecheck-verify-swift -enable-experimental-feature CoroutineFunctions
// REQUIRES; swift_feature_CoroutineFunctions

@yield_once func coro(_ x : inout Float) yields (inout Float) -> () {
  var _x = Float(0.0)
  yield &_x
  x = Float(_x)
}

func retCoro() -> @yield_once (inout Float) yields (inout Float) -> () {
  return coro
}

@yield_once func coroWithResult(_ x : Float) yields (inout Float) -> Float {
  var _x = Float(0.0)
  yield &_x
  return _x
}

func retCoroWithResult() -> @yield_once (Float) yields (inout Float) -> (Float) {
  return coroWithResult
}

@yield_once func coroGen<T>(_ x : inout T) yields (inout T) -> () {
  var _x = x
  yield &_x
  x = _x
}

func retGenCoro<T>() -> @yield_once (inout T) yields (inout T) -> () {
  return coroGen
}

@yield_once func coroGenWithResult<T>(_ x : T) yields (inout T) -> T {
  var _x = x
  yield &_x
  return _x
}

func retCoroGenWithResult<T>() -> @yield_once (T) yields (inout T) -> T {
  return coroGenWithResult
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/coroutines.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-feature CoroutineFunctions %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_CoroutineFunctions
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
