// RUN; %target-typecheck-verify-swift -swift-version 4

extension X { } // expected_error {{cannot find type 'X' in scope}}
_ = 1
f() // expected_error {{cannot find 'f' in scope}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/delayed_extension.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
