// RUN; %target-typecheck-verify-swift

@diagnose(ExistentialAny, as: error)
class Foo {}

@diagnose(ExistentialAny, as: ignored)
struct Bar {}

@diagnose(ExistentialAny, as: warning)
enum Baz {}

@diagnose(ExistentialAny, as: error)
actor Qux {
    @diagnose(ExistentialAny, as: ignored)
    struct Quux {}
}
@diagnose(ExistentialAny, as: warning)
protocol Corge {}

@diagnose(ExistentialAny, as: ignored)
extension Bar {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnose_attr_nominal.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
