// RUN; %target-typecheck-verify-swift

@diagnose(ExistentialAny, as: error)
import Swift

struct garply: ~Copyable {
    @diagnose(ExistentialAny, as: ignored)
    init() {}

    @diagnose(ExistentialAny, as: ignored)
    subscript(index: Int) -> Int {
        return 11
    }

    @diagnose(ExistentialAny, as: ignored)
    var computedProperty: Int {
        return 11
    }

    var property: Int {
        @diagnose(ExistentialAny, as: error)
        get {
            return 11
        }
        @diagnose(ExistentialAny, as: warning)
        set {
            let _ = 11
        }
    }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnose_attr_misc.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
