// RUN; %target-typecheck-verify-swift -swift-version 4

// https://github.com/apple/swift/issues/46040
// See test/Compatibility/enum_element_pattern.swift for Swift3 behavior.
// As for FIXME cases: see https://github.com/apple/swift/issues/46054

enum E {
  case A, B, C, D

  static func testE(e: E) {
    switch e {
    case A<UndefinedTy>(): // expected_error {{cannot find type 'UndefinedTy' in scope}}
    // expected_note@-1 {{while parsing this '<' as a type parameter bracket}}
    // expected_error@-2 {{cannot specialize non-generic type 'E'}}
    // expected_error@-3 {{enum case 'A' has no associated values}}
      break
    case B<Int>(): // expected_error {{cannot specialize non-generic type 'E'}}
    // expected_error@-1 {{enum case 'B' has no associated values}}
      break
    default:
      break;
    }
  }
}

func testE(e: E) {
  switch e {
  case E.A<UndefinedTy>(): // expected_error {{cannot find type 'UndefinedTy' in scope}}
  // expected_note@-1 {{while parsing this '<' as a type parameter bracket}}
  // expected_error@-2 {{cannot specialize non-generic type 'E'}}
  // expected_error@-3 {{enum case 'A' has no associated values}}
    break
  case E.B<Int>(): // expected_error {{cannot specialize non-generic type 'E'}}
  // expected_error@-1 {{enum case 'B' has no associated values}}
    break
  case .C(): // expected_error {{pattern with associated values does not match enum case 'C'}}
             // expected_note@-1 {{remove associated values to make the pattern match}} {{10-12=}} 
    break
  case .D(let payload): // expected_error{{pattern with associated values does not match enum case 'D'}}
                        // expected_note@-1 {{remove associated values to make the pattern match}} {{10-23=}}
    let _: () = payload
    break
  default:
    break
  }

  guard
    case .C() = e, // expected_error {{pattern with associated values does not match enum case 'C'}} 
                   // expected_note@-1 {{remove associated values to make the pattern match}} {{12-14=}}
    case .D(let payload) = e // expected_error {{pattern with associated values does not match enum case 'D'}}
                             // expected_note@-1 {{remove associated values to make the pattern match}} {{12-25=}}
  else { return }
}

extension E : Error {}
func canThrow() throws {
  throw E.A
}

do {
  try canThrow()
} catch E.A() { // expected_error {{pattern with associated values does not match enum case 'A'}}
                // expected_note@-1 {{remove associated values to make the pattern match}} {{12-14=}}
  // ..
} catch E.B(let payload) { // expected_error {{pattern with associated values does not match enum case 'B'}}
                           // expected_note@-1 {{remove associated values to make the pattern match}} {{12-25=}} 
  let _: () = payload
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/enum_element_pattern_swift4.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
