// RUN; %target-typecheck-verify-swift -parse -enable-experimental-feature ExtractConstantsFromMembers

// REQUIRES; swift_feature_ExtractConstantsFromMembers

@extractConstantsFromMembers
protocol MyProto {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/extractConstantsFromMembers_attr.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-feature ExtractConstantsFromMembers %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ExtractConstantsFromMembers
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
