#!/usr/bin/swift
let x = 42
x + x // expected_warning {{result of operator '+' is unused}}
// Check that we skip the hashbang at the beginning of the file.
// RUN; %target-typecheck-verify-swift

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/hashbang_main.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
