// RUN; %target-swift-frontend %s -typecheck -verify

let int: Int = fatalError() // expected_error {{cannot convert value of type 'Never' to specified type 'Int'}}

func explicitReturn() -> Int {
    return fatalError() // expected_error {{cannot convert return expression of type 'Never' to return type 'Int'}}
}

func explicitMultiElement() -> Int {
    print("no way")
    return fatalError() // expected_error {{cannot convert return expression of type 'Never' to return type 'Int'}}
}

func implicitReturn() -> Int {
    fatalError()
}

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/implicit_uninhabited_conversion.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
