// RUN; %target-typecheck-verify-swift \
// RUN;   -enable-experimental-feature LifetimeDependence

// REQUIRES; swift_feature_LifetimeDependence

struct S: ~Escapable {}

func hello(_ t: some Escapable, _ u: any Escapable) {}

protocol Whatever: Escapable {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/inverse_escapable_feature.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-feature LifetimeDependence %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_LifetimeDependence
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
