// RUN; %target-typecheck-verify-swift -enable-library-evolution

#if hasFeature(LibraryEvolution)
#else
#error("Missing feature")
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/library_evolution_feature.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-library-evolution %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
