// RUN; %target-typecheck-verify-swift

// REQUIRES; objc_interop

class C {}
struct S {}

protocol NonClassProto {}
protocol ClassConstrainedProto : class {}

func takesAnyObject(_ x: AnyObject) {}

func concreteTypes() {
  takesAnyObject(C.self) 
  takesAnyObject(S.self) // expected_error{{argument type 'S.Type' expected to be an instance of a class or class-constrained type}}
  takesAnyObject(ClassConstrainedProto.self) // expected_error{{argument type '(any ClassConstrainedProto).Type' expected to be an instance of a class or class-constrained type}}
}

func existentialMetatypes(nonClass: NonClassProto.Type,
                          classConstrained: ClassConstrainedProto.Type,
                          compo: (NonClassProto & ClassConstrainedProto).Type) {
  takesAnyObject(nonClass) // expected_error{{argument type 'any NonClassProto.Type' expected to be an instance of a class or class-constrained type}}
  takesAnyObject(classConstrained)
  takesAnyObject(compo)
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/metatype_object_conversion.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: objc_interop
// parity: passing
// ---- end ASTGen parity ----
