// RUN; %target-swift-frontend -dump-parse %s | %FileCheck %s

// CR
_ = """"""
//CHECK: string_literal_expr {{.*}} value=""

_ = """  test  """
//CHECK: string_literal_expr {{.*}} value="test"

// CR+LF
_ = """
    """
//CHECK: string_literal_expr {{.*}} value=""

_ = """
  test
  """
//CHECK: string_literal_expr {{.*}} value="test"

// CR+LF
_ = """
    """
//CHECK: string_literal_expr {{.*}} value=""
_ = """
  test
  test
  """
//CHECK: string_literal_expr {{.*}} value="test\ntest"

// LF+CR
_ = """
    foo
    foo
    """
//CHECK: string_literal_expr {{.*}} value="\nfoo\n\nfoo\n"

// LF+CR+LF
_ = """

    foo

    foo

    """
//CHECK: string_literal_expr {{.*}} value="\nfoo\n\nfoo\n"

// Mixed no-indent.
_ = """
<LF
<LF<CR
<CR+LF
"""
//CHECK: string_literal_expr {{.*}} value="<LF\n<LF\n<CR\n<CR+LF"

// Mixed indent.
_ = """
	 <LF
	 <LF	 <CR
	 <CR+LF
	 """
//CHECK: string_literal_expr {{.*}} value="<LF\n<LF\n<CR\n<CR+LF"

// Empty line CR, CR+LF, LF.
_ = """
   foo


   bar
   """
//CHECK: string_literal_expr {{.*}} value="foo\n\n\n\nbar"
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/multiline_normalize_newline.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
