// RUN; %target-typecheck-verify-swift -verify-ignore-unrelated -enable-objc-interop

@objc enum Foo: Int32 {
  case Zim, Zang, Zung
}

@objc enum Generic<T>: Int32 { // expected_error{{enum cannot be marked '@objc' because it is generic}} {{1-7=}}
  case Zim, Zang, Zung
}

@objc(EnumRuntimeName) enum RuntimeNamed: Int32 {
  case Zim, Zang, Zung
}

@objc enum NoRawType { // expected_error{{'@objc' enum must declare an integer raw type}}
  case Zim, Zang, Zung
}

@objc enum NonIntegerRawType: Float { // expected_error{{'@objc' enum raw type 'Float' must be an integer type expressible in Objective-C}}
  case Zim = 1.0, Zang = 1.5, Zung = 2.0
}

enum NonObjCEnum: Int {
  case Zim, Zang, Zung
}

class Bar {
  @objc func foo(x: Foo) {}
  @objc func nonObjC(x: NonObjCEnum) {} //expected_error{{type of the parameter cannot be represented in Objective-C}} //expected_note{{Swift enums not marked '@c' or '@objc' cannot be represented in Objective-C}}
}

// <rdar://problem/23681566> @objc enums with payloads rejected with no source location info
@objc enum r23681566 : Int32 {  // expected_error {{'r23681566' declares raw type 'Int32', but does not conform to RawRepresentable and conformance could not be synthesized}} expected_note {{declared raw type 'Int32' here}} expected_note {{add stubs for conformance}}
  case Foo(progress: Int)     // expected_error {{enum with raw type cannot have cases with arguments}}
}

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/objc_enum.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-objc-interop %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
