// RUN; %target-swift-frontend %s -typecheck -verify

func badIs<T>(_ value: Any, anInstanceOf type: T.Type) -> Bool { // expected_note {{'type' declared here}}
    value is type // expected_error {{type-casting operator expects a type on its right-hand side (got: parameter 'type')}}
}

func foo() -> Int {
    return // expected_error {{non-void function should return a value}}
}

func badIs_ifdecl<T>(_ value: Any, anInstanceOf type: T.Type) -> Bool { // expected_note {{'type' declared here}}
    #if true
    value is type // expected_error {{type-casting operator expects a type on its right-hand side (got: parameter 'type')}}
    #endif
}

func foo_ifdecl() -> Int {
    #if true
    return // expected_error {{non-void function should return a value}}
    #endif
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/omit_return_fail.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
