// RUN; %target-typecheck-verify-swift

struct S {
  var x: Int = 0
  let y: Int = 0  // expected_note 3 {{change 'let' to 'var' to make it mutable}} {{3-6=var}} {{3-6=var}} {{3-6=var}}

  mutating func mutateS() {}

  init() {}
}

struct T {
  var mutS: S? = nil
  let immS: S? = nil  // expected_note 4 {{change 'let' to 'var' to make it mutable}} {{3-6=var}} {{3-6=var}} {{3-6=var}} {{3-6=var}}

  mutating func mutateT() {}

  init() {}
}

var mutT: T?
let immT: T? = nil  // expected_note {{change 'let' to 'var' to make it mutable}} {{1-4=var}}

postfix operator ++
prefix operator ++

public postfix func ++ <T>(rhs: inout T) -> T { fatalError() }
public prefix func ++ <T>(rhs: inout T) -> T { fatalError() }

mutT?.mutateT()
immT?.mutateT() // expected_error{{cannot use mutating member on immutable value: 'immT' is a 'let' constant}}
mutT?.mutS?.mutateS()
mutT?.immS?.mutateS() // expected_error{{cannot use mutating member on immutable value: 'immS' is a 'let' constant}}
mutT?.mutS?.x += 1
mutT?.mutS?.y++ // expected_error{{cannot pass immutable value to mutating operator: 'y' is a 'let' constant}}

// Prefix operators don't chain
++mutT?.mutS?.x // expected_error{{cannot pass immutable value of type 'Int?' to mutating operator}}
++mutT?.mutS?.y // expected_error{{cannot pass immutable value of type 'Int?' to mutating operator}}

mutT? = T()
mutT?.mutS = S()
mutT?.mutS? = S()
mutT?.mutS?.x += 0
_ = mutT?.mutS?.x + 0 // expected_error{{value of optional type 'Int?' must be unwrapped}}
// expected_note@-1{{coalesce}}
// expected_note@-2{{force-unwrap}}
mutT?.mutS?.y -= 0 // expected_error{{left side of mutating operator isn't mutable: 'y' is a 'let' constant}}
mutT?.immS = S() // expected_error{{cannot assign to property: 'immS' is a 'let' constant}}
mutT?.immS? = S() // expected_error{{cannot assign to value: 'immS' is a 'let' constant}}
mutT?.immS?.x += 0 // expected_error{{left side of mutating operator isn't mutable: 'immS' is a 'let' constant}}
mutT?.immS?.y -= 0 // expected_error{{left side of mutating operator isn't mutable: 'y' is a 'let' constant}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/optional_chain_lvalues.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
