// RUN; %target-typecheck-verify-swift -parse-as-library

let _ = 1 // expected_error{{global variable declaration does not bind any variables}}

func foo() {
  let _ = 1 // OK
}

struct Foo {
  let _ = 1 // expected_error{{property declaration does not bind any variables}}
  var (_, _) = (1, 2) // expected_error{{property declaration does not bind any variables}}

  func foo() {
    let _ = 1 // OK
  }
}


// <rdar://problem/19786845> Warn on "let" and "var" when no data is bound in a pattern
enum SimpleEnum { case Bar }


func testVarLetPattern(a : SimpleEnum) {
  switch a {
  case let .Bar: break      // expected_warning {{'let' pattern has no effect; sub-pattern didn't bind any variables}} {{8-12=}}
  }
  switch a {
  case let x: _ = x; break         // Ok.
  }
  switch a {
  case let _: break         // expected_warning {{'let' pattern has no effect; sub-pattern didn't bind any variables}} {{8-12=}}
  }
  switch (a, 42) {
  case let (_, x): _ = x; break    // ok
  }
  // expected_warning @+1 {{'if' condition is always true}}
  if case let _ = "str" {}  // expected_warning {{'let' pattern has no effect; sub-pattern didn't bind any variables}} {{11-15=}}
}

// https://github.com/apple/swift/issues/53293
class C_53293 {
  static var _: Int { 0 } //expected_error {{getter/setter can only be defined for a single variable}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/pattern_without_variables.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-as-library %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-error@42:14 {{}} // getset_nontrivial_pattern
// ---- end ASTGen parity ----
