// RUN; %target-typecheck-verify-swift -playground

var a = 1, b = 2
let z = 3

a
(a, b)
(a, z)
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/playground_lvalues.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -playground %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
