// RUN; %target-typecheck-verify-swift
ÿþ // expected_error{{input files must be encoded as UTF-8 instead of UTF-16}}
asdfadf() // no error, the BOM marker causes us to skip to the end
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/utf16_bom.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-error@2:1 {{}} // lex_utf16_bom_marker
// ---- end ASTGen parity ----
