// RUN; %swift -target x86_64-unknown-windows-msvc -parse-stdlib -typecheck -verify %s

// expected_error@+1{{attribute @_weakLinked is unsupported on target 'x86_64-unknown-windows-msvc'}}
@_weakLinked func f() { }

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/weakLinked.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -target x86_64-unknown-windows-msvc -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
