// RUN; %target-typecheck-verify-swift -target %target-swift-5.1-abi-triple

// REQUIRES; concurrency



actor MyActor1 // expected_error {{expected '{' in actor}}

actor MyActor2 { // expected_note@:16 {{to match this opening '{'}}
    init() {
    }
func hello() { } // expected_error@+1 {{expected '}' in actor}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/actor.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -target %target-swift-5.1-abi-triple %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: concurrency
// XFAIL: *
// expected-error@7:15 {{}} // expected_lbrace_actor
// expected-note@9:16 {{}} // opening_brace
// expected-error@24:1 {{}} // expected_rbrace_actor
// ---- end ASTGen parity ----
