// RUN; %target-typecheck-verify-swift

@ MainActor  // expected_warning {{extraneous whitespace between '@' and attribute name; this is an error in the Swift 6 language mode}}
class Foo {
  func funcWithEscapingClosure(_ x: @ escaping () -> Int) {} // expected_warning {{extraneous whitespace between '@' and attribute name; this is an error in the Swift 6 language mode}}
}

@available (*, deprecated) // expected_warning {{extraneous whitespace between attribute name and '('; this is an error in the Swift 6 language mode}}
func deprecated() {}

@propertyWrapper
struct MyPropertyWrapper {
  var wrappedValue: Int = 1

  init(param: Int) {}
}

struct PropertyWrapperTest {
  @MyPropertyWrapper (param: 2)  // expected_warning {{extraneous whitespace between attribute name and '('; this is an error in the Swift 6 language mode}}
  var x: Int

  @MyPropertyWrapper
  (param: 2) // expected_error {{expected 'var' keyword in property declaration}} expected_error {{property declaration does not bind any variables}} expected_error {{expected pattern}}
  var y: Int
}

let closure1 = { @MainActor (a, b) in // expected_warning {{extraneous whitespace between attribute name and '('; this is an error in the Swift 6 language mode}}
}

let closure2 = { @MainActor
  (a: Int, b: Int) in
}

// expected_warning@+1{{extraneous whitespace between '@' and attribute name; this is an error in the Swift 6 language mode}}
@ 
MainActor
func mainActorFunc() {}


@inline // expected_error {{expected '(' in 'inline' attribute}}
(never) func neverInline() {} // expected_error {{expected declaration}}

@objc
(whatever) func whateverObjC() {} // expected_error {{expected declaration}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/attribute_spacing.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-warning@3:2 {{}} // attr_extra_whitespace_after_at
// expected-warning@5:38 {{}} // attr_extra_whitespace_after_at
// expected-warning@8:11 {{}} // attr_extra_whitespace_before_lparen
// expected-warning@19:21 {{}} // attr_extra_whitespace_before_lparen
// expected-error@23:3 {{}} // expected_keyword_in_decl
// expected-error@23:11 {{}} // expected_pattern
// expected-warning@27:28 {{}} // attr_extra_whitespace_before_lparen
// expected-warning@35:2 {{}} // attr_extra_whitespace_after_at
// expected-error@40:2 {{}} // attr_expected_lparen
// expected-error@41:1 {{}} // expected_decl
// expected-error@44:1 {{}} // expected_decl
// ---- end ASTGen parity ----
