// RUN; %target-typecheck-verify-swift -swift-version 6

@ MainActor  // expected_error {{extraneous whitespace between '@' and attribute name}}
class Foo {
  func funcWithEscapingClosure(_ x: @ escaping () -> Int) {} // expected_error {{extraneous whitespace between '@' and attribute name}}
}

@available (*, deprecated) // expected_error {{extraneous whitespace between attribute name and '('}}
func deprecated() {}

@propertyWrapper
struct MyPropertyWrapper {
  var wrappedValue: Int = 1

  init(param: Int) {}
}

struct PropertyWrapperTest {
  @MyPropertyWrapper (param: 2)  // expected_error {{extraneous whitespace between attribute name and '('}}
  var x: Int

  @MyPropertyWrapper
  (param: 2) // expected_error {{expected 'var' keyword in property declaration}} expected_error {{property declaration does not bind any variables}} expected_error {{expected pattern}}
  var y: Int
}

let closure1 = { @MainActor (a, b) in 
// expected_error@-1 {{cannot infer type of closure parameter 'a' without a type annotation}}
// expected_error@-2 {{cannot infer type of closure parameter 'b' without a type annotation}}
}

let closure2 = { @MainActor
  (a: Int, b: Int) in
  let _: Int = a
}

// expected_error@+1 {{extraneous whitespace between '@' and attribute name}}
@ 
MainActor
func mainActorFunc() {}


@inline // expected_error {{expected '(' in 'inline' attribute}}
(never) func neverInline() {} // expected_error {{expected declaration}}

@objc
(whatever) func whateverObjC() {} // expected_error {{expected declaration}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/attribute_spacing_swift6.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 6 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@3:2 {{}} // attr_extra_whitespace_after_at
// expected-error@5:38 {{}} // attr_extra_whitespace_after_at
// expected-error@8:11 {{}} // attr_extra_whitespace_before_lparen
// expected-error@19:21 {{}} // attr_extra_whitespace_before_lparen
// expected-error@23:3 {{}} // expected_keyword_in_decl
// expected-error@23:11 {{}} // expected_pattern
// expected-error@38:2 {{}} // attr_extra_whitespace_after_at
// expected-error@43:2 {{}} // attr_expected_lparen
// expected-error@44:1 {{}} // expected_decl
// expected-error@47:1 {{}} // expected_decl
// ---- end ASTGen parity ----
