// RUN; %target-typecheck-verify-swift

// Make sure source ranges satisfy the verifier.
for foo in [1, 2] { // expected_note {{to match this opening '{'}}
  _ = foo
// expected_error@+1{{expected '}' at end of brace statement}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/brace_recovery_eof.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@4:19 {{}} // opening_brace
// expected-error@16:1 {{}} // expected_rbrace_in_brace_stmt
// ---- end ASTGen parity ----
