// RUN; %target-swift-frontend -parse -verify -swift-version 5 %s

func test<T>(make: () -> [T], consume: (T) -> Void) { consume(make()[0]) }

func main1() {
  test(make: { () -> [Int] // expected_error@+1 {{expected 'in' after the closure signature}}
    return [3]
  }, consume: { _ in })
}


// Resync path: there are tokens before `in` — should diagnose once, then recover.
func main2() {
  _ = { () -> Int
    0 // expected_error {{unexpected tokens prior to 'in'}}
    in
    1
  }
}

func main3() {
  _ = { x, y -> Int
    x + y // expected_error {{expected 'in' after the closure signature}}
  }
}

func ok() {
  _ = { (x: Int) -> Int in x + 1 }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/closure-missing-in.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 5 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@7:5 {{}} // expected_closure_in
// expected-error@15:5 {{}} // unexpected_tokens_before_closure_in
// expected-error@23:5 {{}} // expected_closure_in
// ---- end ASTGen parity ----
