// RUN; %target-typecheck-verify-swift

func statement_starts() {
  var f : (Int) -> ()
  f = { (x : Int) -> () in }

  f(0)
  f (0)
  f // expected_warning{{variable is unused}}
  (0) // expected_warning {{integer literal is unused}}

  var a = [1,2,3]
  a[0] = 1
  a [0] = 1
  a // expected_warning{{variable is unused}}
  [0, 1, 2] // expected_warning {{expression of type '[Int]' is unused}}
}

// Within a function
func test(i: inout Int, j: inout Int) {
  // Okay
  let q : Int; i = j; j = i; _ = q

  if i != j { i = j }

  // Errors
  i = j j = i // expected_error{{consecutive statements}} {{8-8=;}}
  let r : Int i = j // expected_error{{consecutive statements}} {{14-14=;}}
  let s : Int let t : Int // expected_error{{consecutive statements}} {{14-14=;}}
  _ = r; _ = s; _ = t
}

struct X {
  // In a sequence of declarations.
  var a, b : Int func d() -> Int {} // expected_error{{consecutive declarations}} {{17-17=;}}

  var prop : Int { return 4
  } var other : Float // expected_error{{consecutive declarations}} {{4-4=;}}

  // Within property accessors
  subscript(i: Int) -> Float {
    get {
      var x = i x = i + x return Float(x) // expected_error{{consecutive statements}} {{16-16=;}} expected_error{{consecutive statements}} {{26-26=;}}
    }
    set {
      var x = i x = i + 1 // expected_error{{consecutive statements}} {{16-16=;}}
      _ = x
    }
  }
}

class C {
  // In a sequence of declarations.
  var a, b : Int func d() -> Int {} // expected_error{{consecutive declarations}} {{17-17=;}}
  init() {
    a = 0
    b = 0
  }
}

protocol P {
  func a() func b() // expected_error{{consecutive declarations}} {{11-11=;}}
}

enum Color {
  case Red case Blue // expected_error{{consecutive declarations}} {{11-11=;}}
  func a() {} func b() {} // expected_error{{consecutive declarations}} {{14-14=;}}
}

// At the top level
var i, j : Int i = j j = i // expected_error{{consecutive statements}} {{15-15=;}} expected_error{{consecutive statements}} {{21-21=;}}

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/consecutive_statements.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@27:8 {{}} // statement_same_line_without_semi
// expected-error@28:14 {{}} // statement_same_line_without_semi
// expected-error@29:14 {{}} // statement_same_line_without_semi
// expected-error@35:17 {{}} // declaration_same_line_without_semi
// expected-error@38:4 {{}} // declaration_same_line_without_semi
// expected-error@43:16 {{}} // statement_same_line_without_semi
// expected-error@43:26 {{}} // statement_same_line_without_semi
// expected-error@46:16 {{}} // statement_same_line_without_semi
// expected-error@54:17 {{}} // declaration_same_line_without_semi
// expected-error@62:11 {{}} // declaration_same_line_without_semi
// expected-error@66:11 {{}} // declaration_same_line_without_semi
// expected-error@67:14 {{}} // declaration_same_line_without_semi
// expected-error@71:15 {{}} // statement_same_line_without_semi
// expected-error@71:21 {{}} // statement_same_line_without_semi
// ---- end ASTGen parity ----
