// RUN; not %target-swift-frontend -typecheck -diagnostic-style llvm %s 2>&1 | %FileCheck -strict-whitespace %s

// Test the diagnostic option 'PointsToFirstBadToken'.

typealias TestDiagPointsToEndOfLine =

// CHECK: error: expected type in type alias declaration
// CHECK-NEXT: {{^}}typealias TestDiagPointsToEndOfLine ={{$}}
// CHECK-NEXT: {{^}}                                     ^{{$}}

typealias TestDiagPointsToBadToken = =

// CHECK: error: expected type in type alias declaration
// CHECK-NEXT: {{^}}typealias TestDiagPointsToBadToken = ={{$}}
// CHECK-NEXT: {{^}}                                     ^{{$}}

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnostic_points_to_first_bad_token.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@5:38 {{}} // expected_type_in_typealias
// expected-error@11:38 {{}} // expected_type_in_typealias
// ---- end ASTGen parity ----
