// RUN; %target-typecheck-verify-swift -swift-version 5

dynamic func dynamic_replaceable() {

}

@_dynamicReplacement
// expected_error@-1 {{expected '(' in '_dynamicReplacement' attribute}}
func test_dynamic_replacement_for() {
}

@_dynamicReplacement(
// expected_error@-1 {{expected 'for' in '_dynamicReplacement' attribute}}
func test_dynamic_replacement_for2() {
}

@_dynamicReplacement(for: dynamically_replaceable() // expected_note {{to match this opening '('}}
func test_dynamic_replacement_for3() {
// expected_error@-1 {{expected ')' after function name for '@_dynamicReplacement'}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnose_dynamicReplacement.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 5 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@7:2 {{}} // attr_expected_lparen
// expected-error@12:2 {{}} // attr_dynamic_replacement_expected_for
// expected-note@17:21 {{}} // opening_paren
// expected-error@18:1 {{}} // attr_dynamic_replacement_expected_rparen
// ---- end ASTGen parity ----
