// RUN; %target-typecheck-verify-swift

// https://github.com/apple/swift/issues/52877

protocol Brew { // expected_note {{in declaration of 'Brew'}}
  tripel() -> Int // expected_error {{expected 'func' keyword in instance method declaration}} {{3-3=func }}

  quadrupel: Int { get } // expected_error {{expected 'var' keyword in property declaration}} {{3-3=var }}

  static + (lhs: Self, rhs: Self) -> Self // expected_error {{expected 'func' keyword in operator function declaration}} {{10-10=func }}

  * (lhs: Self, rhs: Self) -> Self // expected_error {{expected 'func' keyword in operator function declaration}} {{3-3=func }}
                                   // expected_error @-1 {{operator '*' declared in protocol must be 'static'}} {{3-3=static }}

  ipa: Int { get }; apa: Float { get }
  // expected_error @-1 {{expected 'var' keyword in property declaration}} {{3-3=var }}
  // expected_error @-2 {{expected 'var' keyword in property declaration}} {{21-21=var }}

  stout: Int { get } porter: Float { get }
  // expected_error @-1 {{expected 'var' keyword in property declaration}} {{3-3=var }}
  // expected_error @-2 {{expected declaration}}
  // expected_error @-3 {{consecutive declarations on a line must be separated by ';'}}
}

infix operator %%

struct Bar {
  fisr = 0x5F3759DF // expected_error {{expected 'var' keyword in property declaration}} {{3-3=var }}

  %%<T: Brew> (lhs: T, rhs: T) -> T { // expected_error {{expected 'func' keyword in operator function declaration}} {{3-3=func }}
                                      // expected_error @-1 {{operator '%%' declared in type 'Bar' must be 'static'}}
                                      // expected_error @-2 {{member operator '%%' must have at least one argument of type 'Bar'}}
    lhs + lhs + rhs + rhs
  }

  _: Int = 42 // expected_error {{expected 'var' keyword in property declaration}} {{3-3=var }}
              // expected_error @-1 {{property declaration does not bind any variables}}

  (light, dark) = (100, 200)// expected_error {{expected 'var' keyword in property declaration}} {{3-3=var }}
  
  a, b: Int // expected_error {{expected 'var' keyword in property declaration}} {{3-3=var }}
}

class Baz {

  instanceMethod() {} // expected_error {{expected 'func' keyword in instance method declaration}} {{3-3=func }}

  static staticMethod() {} // expected_error {{expected 'func' keyword in static method declaration}} {{10-10=func }}

  instanceProperty: Int { 0 } // expected_error {{expected 'var' keyword in property declaration}} {{3-3=var }}

  static staticProperty: Int { 0 } // expected_error {{expected 'var' keyword in static property declaration}} {{10-10=var }}
}

class C1 {
  class classMethod() {} // expected_error {{expected '{' in class}}
}

class C2 {
  class classProperty: Int { 0 } // expected_error {{inheritance from non-protocol, non-class type 'Int'}}
                                 // expected_note @-1 {{in declaration of 'classProperty'}}
                                 // expected_error @-2 {{expected declaration}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnostic_missing_func_keyword.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@5:10 {{}} // note_in_decl_of
// expected-error@6:3 {{}} // expected_keyword_in_decl
// expected-error@8:3 {{}} // expected_keyword_in_decl
// expected-error@10:10 {{}} // expected_keyword_in_decl
// expected-error@12:3 2 {{}} // expected_keyword_in_decl,operator_static_in_protocol
// expected-error@15:3 {{}} // expected_keyword_in_decl
// expected-error@15:21 {{}} // expected_keyword_in_decl
// expected-error@19:3 {{}} // expected_keyword_in_decl
// expected-error@19:21 {{}} // declaration_same_line_without_semi
// expected-error@19:22 {{}} // expected_decl
// expected-error@28:3 {{}} // expected_keyword_in_decl
// expected-error@30:3 {{}} // expected_keyword_in_decl
// expected-error@36:3 {{}} // expected_keyword_in_decl
// expected-error@39:3 {{}} // expected_keyword_in_decl
// expected-error@41:3 {{}} // expected_keyword_in_decl
// expected-error@46:3 {{}} // expected_keyword_in_decl
// expected-error@48:10 {{}} // expected_keyword_in_decl
// expected-error@50:3 {{}} // expected_keyword_in_decl
// expected-error@52:10 {{}} // expected_keyword_in_decl
// expected-error@56:20 {{}} // expected_lbrace_class
// expected-note@60:9 {{}} // note_in_decl_of
// expected-error@60:30 {{}} // expected_decl
// ---- end ASTGen parity ----
