// RUN; %target-swift-frontend -dump-parse -verify %s > /dev/null

func discard<T>(_ t: T) {}

func a() {
  discard case // expected_error {{'case' label can only appear inside a 'switch' statement}}
  // expected_error@-1 {{consecutive statements on a line must be separated by ';'}}
}

func b() {
  discard 124 // expected_error {{consecutive statements on a line must be separated by ';'}}
}

func c() {
  discard where 5 == 0 // expected_error {{expected expression}}
  // expected_error@-1 {{consecutive statements on a line must be separated by ';'}}
}

func c() {
  // sticking a let here to ensure the parser is treating this like an expr.
  let _ = discard ++ something
}

func c() {
  let _ = discard self // expected_error {{consecutive statements on a line must be separated by ';'}}
}

func c() {
  discard Self
}

func c() {
  discard self
}

func c() {
  _forget self  // expected_error {{consecutive statements on a line must be separated by ';'}}
}

func c() {
  discard `self`
}

func c() {
  discard switch  // expected_error {{expected expression in 'switch' statement}}
  // expected_error@-1 {{consecutive statements on a line must be separated by ';'}}
}

func c() {
  discard SarahMarshall
}

func c() {
  discard x.y.z
}

func c() {
  discard discard self // expected_error {{consecutive statements on a line must be separated by ';'}}
}

class discard {
  func discard() {
    discard discard(self)

    let _ = discard()

    let _ = discard{
      discard   {
        discard itALL
      }
    }
  }

  var x: Int {
    get {
      discard self.x()
    }
  }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/discard.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@6:10 {{}} // statement_same_line_without_semi
// expected-error@6:11 {{}} // case_outside_of_switch
// expected-error@11:10 {{}} // statement_same_line_without_semi
// expected-error@15:10 {{}} // statement_same_line_without_semi
// expected-error@15:11 {{}} // expected_expr
// expected-error@25:18 {{}} // statement_same_line_without_semi
// expected-error@37:10 {{}} // statement_same_line_without_semi
// expected-error@45:10 {{}} // statement_same_line_without_semi
// expected-error@45:17 {{}} // expected_switch_expr
// expected-error@58:18 {{}} // statement_same_line_without_semi
// ---- end ASTGen parity ----
