// RUN; %target-typecheck-verify-swift

func foo(x: Int) {}
foo(: 1) // expected_error{{expected argument label before colon}} expected_error{{missing argument label 'x:' in call}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/function_call.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:5 {{}} // expected_label_before_colon
// ---- end ASTGen parity ----
