// RUN; %target-swift-frontend -parse -verify %s

// No more diags expected during Sema.
// RUN; %target-typecheck-verify-swift

do {
  func something() -> Bool {}
  func foo() {}

  do {
    if something() {
    // expected_error@+1:11 {{expected '{' or 'if' after 'else'}}{{none}}
    } else
  }

  do {
    if something() {
    // expected_error@+1:11 {{expected '{' or 'if' after 'else'}}{{none}}
    } else
    foo()
  }

  do {
    if something() {
    // expected_error@+1:7 {{expected '{' or 'if' after 'else'; did you mean to write 'if'?}}{{11-11= if}}
    } else something() { // Fix-it because all on one line.
    }
  }

  do {
    if something() {
    // expected_error@+1:12 {{expected '{' or 'if' after 'else'}}{{none}}
    } else something()
    {
    }
  }

 do {
    if something() {
    // expected_error@+1:12 {{expected '{' or 'if' after 'else'}}{{none}}
    } else something()
    foo1()
  }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/if-else-invalid.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@13:11 {{}} // expected_lbrace_or_if_after_else
// expected-error@19:11 {{}} // expected_lbrace_or_if_after_else
// expected-error@26:7 {{}} // expected_lbrace_or_if_after_else_fixit
// expected-error@33:12 {{}} // expected_lbrace_or_if_after_else
// expected-error@41:12 {{}} // expected_lbrace_or_if_after_else
// ---- end ASTGen parity ----
