// RUN; %target-typecheck-verify-swift

func test1() {
  var a : Int {
#if arch(x86_64)
    return 0
#else
    return 1
#endif
  }
}

// Would trigger assertion when AST verifier checks source ranges ("child source range not contained within its parent")
func test2() { // expected_note {{match}}
  var a : Int { // expected_note {{match}} expected_note {{'a' declared here}}
    switch i { // expected_error {{cannot find 'i' in scope; did you mean 'a'}} expected_error{{'switch' statement body must have at least one 'case'}}
}
// expected_error@+1 2 {{expected '}'}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/implicit_getter_incomplete.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@14:14 {{}} // opening_brace
// expected-note@15:15 {{}} // opening_brace
// expected-error@29:1 2 {{}} // expected_rbrace_in_brace_stmt
// ---- end ASTGen parity ----
