// RUN; %target-typecheck-verify-swift

let a: 123 // expected_error {{consecutive statements on a line must be separated by ';'}}
           // expected_error@-1 {{expected type}}
           // expected_warning@-2 {{integer literal is unused}}

let b: -123 // expected_error {{consecutive statements on a line must be separated by ';'}}
           // expected_error@-1 {{expected type}}
           // expected_warning@-2 {{integer literal is unused}}

let c: -Int // expected_error {{expected type}}
            // expected_error@-1 {{consecutive statements on a line must be separated by ';'}}
            // expected_error@-2 {{unary operator '-' cannot be applied to an operand of type 'Int.Type'}}

struct Generic<T> {}
extension Generic where T == 123 {} // expected_error {{cannot constrain type parameter 'T' to be integer '123'}}

extension Generic where T == -123 {} // expected_error {{cannot constrain type parameter 'T' to be integer '-123'}}

extension Generic where T == -Int {} // expected_error {{expected type}}
                                     // expected_error@-1 {{expected '{' in extension}}

let d = Generic<123>.self // expected_error {{cannot use value type '123' for generic argument 'T'}}

// FIXME: This should at least be parsable...?
let e = Generic<-123>.self // expected_error {{missing whitespace between '<' and '-' operators}}
                           // expected_error@-1 {{'>' is not a postfix unary operator}}

let f = Generic<-Int>.self // expected_error {{missing whitespace between '<' and '-' operators}}
                           // expected_error@-1 {{'>' is not a postfix unary operator}}

let g: 123.Type // expected_error {{consecutive statements on a line must be separated by ';'}}
                // expected_error@-1 {{expected type}}
                // expected_error@-2 {{value of type 'Int' has no member 'Type'}}

let h: 123.Protocol // expected_error {{consecutive statements on a line must be separated by ';'}}
                    // expected_error@-1 {{expected type}}
                    // expected_error@-2 {{value of type 'Int' has no member 'Protocol'}}

let i: 123? // expected_error {{consecutive statements on a line must be separated by ';'}}
            // expected_error@-1 {{expected type}}
            // expected_error@-2 {{cannot use optional chaining on non-optional value of type 'Int'}}

let j: 123! // expected_error {{consecutive statements on a line must be separated by ';'}}
            // expected_error@-1 {{expected type}}
            // expected_error@-2 {{cannot force unwrap value of non-optional type 'Int'}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/integer_types.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@3:7 {{}} // statement_same_line_without_semi
// expected-error@3:8 {{}} // expected_type
// expected-error@7:7 {{}} // statement_same_line_without_semi
// expected-error@7:8 {{}} // expected_type
// expected-error@11:7 {{}} // statement_same_line_without_semi
// expected-error@11:8 {{}} // expected_type
// expected-error@20:30 2 {{}} // expected_lbrace_extension,expected_type
// expected-error@32:7 {{}} // statement_same_line_without_semi
// expected-error@32:8 {{}} // expected_type
// expected-error@36:7 {{}} // statement_same_line_without_semi
// expected-error@36:8 {{}} // expected_type
// expected-error@40:7 {{}} // statement_same_line_without_semi
// expected-error@40:8 {{}} // expected_type
// expected-error@44:7 {{}} // statement_same_line_without_semi
// expected-error@44:8 {{}} // expected_type
// ---- end ASTGen parity ----
