// RUN; %target-swift-frontend -parse -verify %s

func memberwiseInit() {} // dummy symbol
func stringify() {} // dummy symbol

extension String {
  static let bar = #stringify(4)

  #memberwiseInit

  #memberwiseInit { "abc" }

  #memberwiseInit(flavor: .chocolate)

  #memberwiseInit(flavor: .chocolate, haha: true)

  #memberwiseInit(flavor: .chocolate, haha: true) { "abc" }

  @available(macOS 999, *)
  public #memberwiseInit()

  static internal #memberwiseInit

  struct Foo {
    #memberwiseInit

    // expected_error @+1 {{expected a macro identifier for a pound literal declaration}}
    #-
  }

  // expected_error @+1 {{expected a macro identifier for a pound literal declaration}}
  #()
}

@RandomAttr #someFunc

public #someFunc

#someFunc

func test() {
  @discardableResult #someFunc

  dynamic #someFunc

  @CustomAttr
  #someFunc
}

public # someFunc // expected_error {{extraneous whitespace between '#' and macro name is not permitted}} {{9-10=}}

struct S {
  # someFunc // expected_error {{extraneous whitespace between '#' and macro name is not permitted}} {{4-5=}}
  #class
  # struct Inner {} // expected_error {{expected a macro identifier for a pound literal declaration}} expected_error {{consecutive declarations on a line}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/macro_decl.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@28:6 {{}} // macro_expansion_decl_expected_macro_identifier
// expected-error@32:4 {{}} // macro_expansion_decl_expected_macro_identifier
// expected-error@50:9 {{}} // extra_whitespace_macro_expansion_identifier
// expected-error@53:4 {{}} // extra_whitespace_macro_expansion_identifier
// expected-error@55:4 {{}} // declaration_same_line_without_semi
// expected-error@55:5 {{}} // macro_expansion_decl_expected_macro_identifier
// ---- end ASTGen parity ----
