// RUN; %target-swift-frontend -parse -verify %s

#macro

#macro(1)

#macro(1, 2)

_ = #macro(1, 2, 3)

_ = #trailing {
  1
}

_ = #trailing() {
  1
}

_ = #trailing(x) {
  1
}

_ = #trailing(x, y, z) {
  1
} again: {
  2
} yetAgain: {
  3
}

_ = #another {
  // expected_error @+1 {{expected a macro identifier}}
  #-
}

// expected_error @+1 {{expected a macro identifier for a pound literal expression}}
_ = #()

do {
  _ = # // expected_error {{expected a macro identifier for a pound literal expression}}
  name()
}
do {
  _ = # macro() // expected_error {{extraneous whitespace between '#' and macro name is not permitted}} {{8-9=}}
}
do {
  _ = #public()
}
do {
  _ = # public() // expected_error {{expected a macro identifier for a pound literal expression}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/macro_expr.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@33:4 {{}} // macro_expansion_expr_expected_macro_identifier
// expected-error@37:6 {{}} // macro_expansion_expr_expected_macro_identifier
// expected-error@40:8 {{}} // macro_expansion_expr_expected_macro_identifier
// expected-error@44:8 {{}} // extra_whitespace_macro_expansion_identifier
// expected-error@50:9 {{}} // macro_expansion_expr_expected_macro_identifier
// ---- end ASTGen parity ----
