// RUN; %target-typecheck-verify-swift

let nonBreakingSpace1 = 3 // expected_warning {{non-breaking space (U+00A0) used instead of regular space}} {{22-24= }}

let nonBreakingSpace2 = 3 // expected_warning {{non-breaking space (U+00A0) used instead of regular space}} {{24-26= }}

func foo() {
    _ = 42 // expected_warning {{non-breaking space (U+00A0) used instead of regular space}} {{1-9=    }}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/nonbreaking_space.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-warning@3:22 {{}} // lex_nonbreaking_space
// expected-warning@5:24 {{}} // lex_nonbreaking_space
// expected-warning@8:1 {{}} // lex_nonbreaking_space
// ---- end ASTGen parity ----
