// RUN; %target-typecheck-verify-swift

let _ = #notAPound // expected_error {{no macro named 'notAPound'}}
let _ = #notAPound(1, 2) // expected_error {{no macro named 'notAPound'}}
let _ = #Color // expected_error {{no macro named 'Color'}}

let _ = [##] // expected_error {{expected a macro identifier}} {{none}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/object_literals.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@7:11 {{}} // macro_expansion_expr_expected_macro_identifier
// ---- end ASTGen parity ----
