// RUN; %target-typecheck-verify-swift -enable-experimental-static-assert

#assert(true, 123) // expected_error{{expected a string literal}}

#assert(true, "error \(1) message") // expected_error{{'#assert' message cannot be an interpolated string literal}}

#assert true, "error message") // expected_error{{expected '(' in #assert directive}}

#assert(, "error message") // expected_error{{expected a condition expression}}

func unbalanced1() {
  #assert(true // expected_error{{expected ')' in #assert directive}}
  // expected_note @-1 {{to match this opening '('}}
}

func unbalanced2() {
  #assert(true, "hello world" // expected_error{{expected ')' in #assert directive}}
  // expected_note @-1 {{to match this opening '('}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/pound_assert.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-static-assert %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@3:15 {{}} // pound_assert_expected_string_literal
// expected-error@5:15 {{}} // forbidden_interpolated_string
// expected-error@7:9 {{}} // pound_assert_expected_lparen
// expected-error@9:9 {{}} // pound_assert_expected_expression
// expected-note@12:10 {{}} // opening_paren
// expected-error@12:15 {{}} // pound_assert_expected_rparen
// expected-note@17:10 {{}} // opening_paren
// expected-error@17:30 {{}} // pound_assert_expected_rparen
// ---- end ASTGen parity ----
