// RUN; %target-typecheck-verify-swift

// expected_error@+2 {{unterminated string literal}}
// expected_error@+1 {{invalid escape sequence in literal}}
_ = "foo \

// NOTE: DO NOT add a newline at EOF.
// expected_error@+2 {{unterminated string literal}}
// expected_error@+1 {{invalid escape sequence in literal}}
_ = "foo \
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/string_literal_eof3.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@5:5 {{}} // lex_unterminated_string
// expected-error@5:11 {{}} // lex_invalid_escape
// expected-error@10:5 {{}} // lex_unterminated_string
// expected-error@10:11 {{}} // lex_invalid_escape
// ---- end ASTGen parity ----
