// RUN; %target-typecheck-verify-swift

// NOTE: DO NOT add a newline at EOF.
// expected_error@+2 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error@+1 {{unterminated string literal}}
_ = "foo\("bar
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/string_literal_eof2.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@6:5 {{}} // lex_unterminated_string
// expected-error@6:10 {{}} // string_interpolation_unclosed
// ---- end ASTGen parity ----
