// RUN; %target-typecheck-verify-swift

// expected_error@+4 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error@+1 {{unterminated string literal}} expected_error@+3 {{unterminated string literal}}
_ = """
    foo
    \("bar
    baz

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/string_literal_eof7.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@5:5 {{}} // lex_unterminated_string
// expected-error@7:6 {{}} // string_interpolation_unclosed
// expected-error@7:11 {{}} // lex_unterminated_string
// ---- end ASTGen parity ----
