// RUN; %target-typecheck-verify-swift

// NOTE: DO NOT add a newline at EOF.
// expected_error@+1 {{unterminated string literal}}
_ = """
    foo
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/string_literal_eof4.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@5:5 {{}} // lex_unterminated_string
// ---- end ASTGen parity ----
