// RUN; %target-typecheck-verify-swift

struct X { } // expected_note {{did you mean}}

// Simple examples
struct X1 {
  var stored: Int

  subscript(i: Int) -> Int {
    get {
      return stored
    }
    mutating
    set {
      stored = newValue
    }
  }
}

struct X2 {
  var stored: Int

  subscript(i: Int) -> Int {
    get {
      return stored + i
    }
    set(v) {
      stored = v - i
    }
  }
}

struct X3 {
  var stored: Int

  subscript(_: Int) -> Int {
    get {
      return stored
    }
    set(v) {
      stored = v
    }
  }
}

struct X4 {
  var stored: Int

  subscript(i: Int, j: Int) -> Int {
    get {
      return stored + i + j
    }
    mutating
    set(v) {
      stored = v + i - j
    }
  }
}

struct X5 {
  static var stored: Int = 1

  static subscript(i: Int) -> Int {
    get {
      return stored + i
    }
    set {
      stored = newValue - i
    }
  }
}

class X6 {
  static var stored: Int = 1

  class subscript(i: Int) -> Int {
    get {
      return stored + i
    }
    set {
      stored = newValue - i
    }
  }
}

struct Y1 {
  var stored: Int
  subscript(_: i, j: Int) -> Int { // expected_error {{cannot find type 'i' in scope}}
    get {
      return stored + j
    }
    set {
      stored = j
    }
  }
}

// Mutating getters on constants
// https://github.com/apple/swift/issues/43457

struct Y2 {
  subscript(_: Int) -> Int {
    mutating get { return 0 }
  }
}

// FIXME: This test case does not belong in Parse/
let y2 = Y2() // expected_note{{change 'let' to 'var' to make it mutable}}{{1-4=var}}
_ = y2[0] // expected_error{{cannot use mutating getter on immutable value: 'y2' is a 'let' constant}}

// Parsing errors
struct A0 {
  subscript // expected_error {{expected '(' for subscript parameters}}
    i : Int
     -> Int {
    get {
      return stored
    }
    set {
      stored = value
    }
  }

  subscript -> Int { // expected_error {{expected '(' for subscript parameters}} {{12-12=()}}
    return 1
  }
}

struct A1 {
  subscript (i : Int) // expected_error{{expected '->' for subscript element type}}
     Int {
    get {
      return stored // expected_error{{cannot find 'stored' in scope}}
    }
    set {
      stored = newValue// expected_error{{cannot find 'stored' in scope}}
    }
  }
}

struct A2 {
  subscript (i : Int) -> // expected_error{{expected subscripting element type}}
     {
    get {
      return stored // expected_error {{cannot find 'stored' in scope}}
    }
    set {
      stored = newValue // expected_error{{cannot find 'stored' in scope}}
    }
  }
}

struct A3 {
  subscript(i : Int) // expected_error {{expected '->' for subscript element type}}
                     // expected_error@-1 {{expected subscripting element type}}
  {
    get {
      return i
    }
  }
}

struct A4 {
  subscript(i : Int) { // expected_error {{expected '->' for subscript element type}}
                       // expected_error@-1 {{expected subscripting element type}}
    get {
      return i
    }
  }
}

struct A5 {
  subscript(i : Int) -> Int // expected_error {{expected '{' in subscript to specify getter and setter implementation}}
}

struct A6 {
  subscript(i: Int)(j: Int) -> Int { // expected_error {{expected '->' for subscript element type}}
                                     // expected_error@-1 {{function types cannot have argument labels}}
                                     // expected_note@-2 {{did you mean}}
    get {
      return i + j // expected_error {{cannot find 'j' in scope}}
    }
  }
}

struct A7 {
  class subscript(a: Float) -> Int { // expected_error {{class subscripts are only allowed within classes; use 'static' to declare a static subscript}} {{3-8=static}}
    get {
      return 42
    }
  }
}

class A7b {
  class static subscript(a: Float) -> Int { // expected_error {{'static' cannot appear after another 'static' or 'class' keyword}} {{9-16=}}
    get {
      return 42
    }
  }
}

struct A8 {
  subscript(i : Int) -> Int // expected_error{{expected '{' in subscript to specify getter and setter implementation}}
    get {
      return stored
    }
    set {
      stored = value
    }
  }

struct A9 {
  subscript x() -> Int { // expected_error {{subscripts cannot have a name}} {{13-14=}}
    return 0
  }
}

struct A10 {
  subscript x(i: Int) -> Int { // expected_error {{subscripts cannot have a name}} {{13-14=}}
    return 0
  }
  subscript x<T>(i: T) -> Int { // expected_error {{subscripts cannot have a name}} {{13-14=}}
    return 0
  }
}

struct A11 {
  subscript x y : Int -> Int { // expected_error {{expected '(' for subscript parameters}}
    return 0
  }
}

} // expected_error{{extraneous '}' at top level}} {{1-3=}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/subscripting.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@113:12 {{}} // expected_lparen_subscript
// expected-error@124:13 {{}} // expected_lparen_subscript
// expected-error@130:22 {{}} // expected_arrow_subscript
// expected-error@142:25 {{}} // expected_type_subscript
// expected-error@154:21 2 {{}} // expected_arrow_subscript,expected_type_subscript
// expected-error@164:22 2 {{}} // expected_arrow_subscript,expected_type_subscript
// expected-error@173:28 {{}} // expected_lbrace_subscript
// expected-error@177:20 {{}} // expected_arrow_subscript
// expected-error@177:21 {{}} // function_type_argument_label
// expected-error@187:9 {{}} // class_subscript_not_in_class
// expected-error@195:9 {{}} // decl_already_static
// expected-error@203:28 {{}} // expected_lbrace_subscript
// expected-error@213:13 {{}} // subscript_has_name
// expected-error@219:13 {{}} // subscript_has_name
// expected-error@222:13 {{}} // subscript_has_name
// expected-error@228:13 {{}} // expected_lparen_subscript
// expected-error@233:1 {{}} // extra_rbrace
// ---- end ASTGen parity ----
