// RUN; %target-typecheck-verify-swift

class B {
  var foo: Int
  func bar() {}

  init() {} // expected_note {{found this candidate}}
  init(x: Int) {} // expected_note {{found this candidate}}

  subscript(x: Int) -> Int {
    get {}
    set {}
  }
}

class D : B {
  override init() {
    super.init()
    super.init(42)
    // expected_error@-1 {{missing argument label 'x:' in call}}
  }

  override init(x:Int) {
    let _: () -> B = super.init // expected_error {{cannot reference 'super.init' initializer chain as function value}}
  }

  convenience init(y:Int) {
    let _: () -> D = self.init // expected_error {{cannot reference 'self.init' initializer delegation as function value}}
  }

  init(z: Int) {
    super
      .init(x: z)
  }

  func super_calls() {
    super.foo        // expected_warning {{property is accessed but result is unused}}
    super.foo.bar    // expected_error {{value of type 'Int' has no member 'bar'}}
    super.bar        // expected_error {{function is unused}}
    super.bar()
    // FIXME: should also say "'super.init' cannot be referenced outside of an initializer"
    super.init // expected_error{{no exact matches in reference to initializer}}
    super.init() // expected_error{{'super.init' cannot be called outside of an initializer}}
    super.init(0) // expected_error{{'super.init' cannot be called outside of an initializer}} // expected_error {{missing argument label 'x:' in call}}
    super[0]        // expected_warning {{subscript is accessed but result is unused}}
    super
      .bar()
  }

  func bad_super_1() {
    super.$0 // expected_error{{expected identifier or 'init'}}
  }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/super.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@51:11 {{}} // expected_identifier_after_super_dot_expr
// ---- end ASTGen parity ----
