// RUN; %target-swift-frontend -typecheck -verify -swift-version 4 %s

protocol Operator {
  func +(lhs: Self, rhs: Self) -> Self // expected_error {{operator '+' declared in protocol must be 'static'}}
}

func foo(x: Int..., _: String) {} // expected_error {{a parameter following a variadic parameter requires a label}}

protocol P1 {}
protocol P2 {}

let x: protocol<> // expected_error {{'protocol<>' syntax has been removed; use 'Any' instead}}
let y: protocol<P1> // expected_error {{'protocol<...>' composition syntax has been removed and is not needed here}}}
let z: protocol<P1, P2> // expected_error {{'protocol<...>' composition syntax has been removed; join the type constraints using '&'}}

func bar(f: @noescape () -> ()) {} // expected_error {{unknown attribute 'noescape'}}

func baz(f: @autoclosure(escaping) () -> ()) {}
// expected_error @-1 {{cannot find type 'escaping' in scope}}
// expected_error @-2 {{unnamed parameters must be written with the empty name '_'}}
// expected_error @-3 {{expected ',' separator}}

prefix operator +++ {} // expected_error {{operator should no longer be declared with body}}
postfix operator +++ {} // expected_error {{operator should no longer be declared with body}}
infix operator +++ {} // expected_error {{operator should no longer be declared with body}}
infix operator +++* { // expected_error {{operator should no longer be declared with body; use a precedence group instead}}
  associativity right
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/swift3_warnings_swift4_errors_version_4.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:8 {{}} // operator_static_in_protocol
// expected-error@12:8 {{}} // deprecated_any_composition
// expected-error@13:8 {{}} // deprecated_protocol_composition_single
// expected-error@14:8 {{}} // deprecated_protocol_composition
// expected-error@16:13 {{}} // unknown_attr_name
// expected-error@18:36 2 {{}} // expected_separator,parameter_unnamed
// expected-error@23:21 {{}} // deprecated_operator_body
// expected-error@24:22 {{}} // deprecated_operator_body
// expected-error@25:20 {{}} // deprecated_operator_body
// expected-error@26:21 {{}} // deprecated_operator_body_use_group
// ---- end ASTGen parity ----
