// RUN; %target-typecheck-verify-swift

// <rdar://problem/15971438> Incomplete switch was parsing to an AST that
// triggered an assertion failure.
// expected_error@+1 {{switch must be exhaustive}} expected_note@+1{{add a default clause}}
switch 1 { // expected_note{{to match this opening '{'}}
case 1:    // expected_error@+1{{expected '}' at end of 'switch' statement}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/switch_incomplete.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@6:10 {{}} // opening_brace
// expected-error@17:1 {{}} // expected_rbrace_switch
// ---- end ASTGen parity ----
