// RUN; %target-typecheck-verify-swift

struct S {
  var a : Int ;
  func b () {};
  static func c () {};
}

struct SpuriousSemi {
  ; // expected_error{{unexpected ';' separator}} {{3-5=}}
  var a : Int ; ; // expected_error{{unexpected ';' separator}} {{17-19=}}
  func b () {};
  ; static func c () {};  // expected_error{{unexpected ';' separator}} {{3-5=}}
  ;;
  // expected_error @-1 {{unexpected ';' separator}} {{3-4=}}
  // expected_error @-2 {{unexpected ';' separator}} {{4-5=}}
}

class C {
  var a : Int = 10 func aa() {}; // expected_error {{consecutive declarations on a line must be separated by ';'}} {{19-19=;}}
#if FLAG1
  var aaa: Int = 42 func aaaa() {}; // expected_error {{consecutive declarations on a line must be separated by ';'}} {{20-20=;}}
#elseif FLAG2
  var aaa: Int = 42 func aaaa() {} // expected_error {{consecutive declarations on a line must be separated by ';'}} {{20-20=;}}
#else
  var aaa: Int = 42 func aaaa() {} // expected_error {{consecutive declarations on a line must be separated by ';'}} {{20-20=;}}
#endif

  func b () {};
  class func c () {};
}

extension S {
  //var a : Int ;
  func bb () {};
  static func cc () {};
  func dd() {} subscript(i: Int) -> Int { return 1 } // expected_error {{consecutive declarations on a line must be separated by ';'}} {{15-15=;}}
}

protocol P {
  var a : Int { get };
  func b ();
  static func c ();
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/trailing-semi.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@10:3 {{}} // unexpected_separator
// expected-error@11:17 {{}} // unexpected_separator
// expected-error@13:3 {{}} // unexpected_separator
// expected-error@14:3 {{}} // unexpected_separator
// expected-error@14:4 {{}} // unexpected_separator
// expected-error@20:19 {{}} // declaration_same_line_without_semi
// expected-error@22:20 {{}} // declaration_same_line_without_semi
// expected-error@24:20 {{}} // declaration_same_line_without_semi
// expected-error@26:20 {{}} // declaration_same_line_without_semi
// expected-error@37:15 {{}} // declaration_same_line_without_semi
// ---- end ASTGen parity ----
