// RUN; %target-typecheck-verify-swift -target %target-swift-5.9-abi-triple

protocol P {}

protocol P1 {
  associatedtype each A // expected_error {{associated types cannot be variadic}}{{18-23=}}
  associatedtype each B<U>
  // expected_error@-1 {{associated types cannot be variadic}}{{18-23=}}
  // expected_error@-2 {{associated types must not have a generic parameter list}}{{24-27=}}
  associatedtype C... // expected_error {{associated types cannot be variadic}}{{19-22=}}
  associatedtype D<U>...
  // expected_error@-1 {{associated types cannot be variadic}}{{22-25=}}
  // expected_error@-2 {{associated types must not have a generic parameter list}}{{19-22=}}
}

typealias Alias<each T> = (repeat each T)

struct S1<each T> {}
struct S2<T, each U> {}
struct S3<each T, U> {}

struct S4<each T:P, U> {}
struct S5<each T :P, U> {}
struct S6<each T: P> {}
struct S7<each T : P> {}

func foo<each T>(_ x: repeat each T) {}

func bar<each T:P>(_ x: repeat each T) {}
func baz<each T :P>(_ x: repeat each T) {}
func qux<each T : P>(_ x: repeat each T) {}
func quux<each T: P>(_ x: repeat each T) {}

func foobar<T, U, each V>(x: T, y: U, z: repeat each V) { }
func foobaz<T, each U, V>(x: T, y: repeat each U, z: V) { }
func fooqux<each T, each U, each V>(x: repeat each T, y: repeat each U, z: repeat each V) { }

func ellipsis<T...>(_ x: repeat each T) {}
// expected_error@-1 {{ellipsis operator cannot be used with a type parameter pack}}{{16-19=}}{{15-15=each }}
// expected_error@-2 {{cannot find type 'T' in scope}}
func eachEllipsis<each T...>(_ x: repeat each T) {}
// expected_error@-1 {{ellipsis operator cannot be used with a type parameter pack}}{{25-28=}}
// expected_error@-2 {{cannot find type 'T' in scope}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/type_parameter_packs.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -target %target-swift-5.9-abi-triple %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@6:18 {{}} // associatedtype_cannot_be_variadic
// expected-error@7:18 {{}} // associatedtype_cannot_be_variadic
// expected-error@7:24 {{}} // associated_type_generic_parameter_list
// expected-error@10:19 {{}} // associatedtype_cannot_be_variadic
// expected-error@11:19 {{}} // associated_type_generic_parameter_list
// expected-error@11:22 {{}} // associatedtype_cannot_be_variadic
// expected-error@38:19 {{}} // type_parameter_pack_ellipsis
// expected-error@41:28 {{}} // type_parameter_pack_ellipsis
// ---- end ASTGen parity ----
