// RUN; %target-typecheck-verify-swift

//===--- Simple positive tests.

typealias IntPair = (Int, Int)
typealias IntTriple = (Int, Int, Int)
typealias FiveInts = (IntPair, IntTriple)
var fiveInts : FiveInts = ((4,2), (1,2,3))


// <rdar://problem/13339798> QoI: poor diagnostic in malformed typealias
typealias Foo1 : Int  // expected_error {{expected '=' in type alias declaration}} {{16-17==}}
typealias Foo2: Int  // expected_error {{expected '=' in type alias declaration}} {{15-16= =}}
typealias Foo3 :Int  // expected_error {{expected '=' in type alias declaration}} {{16-17== }}
typealias Foo4:/*comment*/Int  // expected_error {{expected '=' in type alias declaration}} {{15-16= = }}

//===--- Tests for error recovery.

typealias Recovery1 // expected_error {{expected '=' in type alias declaration}}

typealias Recovery2 : // expected_error {{expected '=' in type alias declaration}}
// expected_error @-1 {{expected type in type alias declaration}}

typealias Recovery3 = // expected_error {{expected type in type alias declaration}}

typealias Recovery4 : Int // expected_error {{expected '=' in type alias declaration}}

typealias Recovery5 : Int, Float // expected_error {{expected '=' in type alias declaration}}
// expected_error @-1 {{consecutive statements on a line must be separated by ';'}}
// expected_error @-2 {{expected expression}}

typealias Recovery6 = = // expected_error {{expected type in type alias declaration}}

typealias switch = Int // expected_error {{keyword 'switch' cannot be used as an identifier here}} expected_note {{if this name is unavoidable, use backticks to escape it}} {{11-17=`switch`}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/typealias.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@12:16 {{}} // expected_equal_in_typealias
// expected-error@13:15 {{}} // expected_equal_in_typealias
// expected-error@14:16 {{}} // expected_equal_in_typealias
// expected-error@15:15 {{}} // expected_equal_in_typealias
// expected-error@19:20 {{}} // expected_equal_in_typealias
// expected-error@21:21 {{}} // expected_equal_in_typealias
// expected-error@21:22 {{}} // expected_type_in_typealias
// expected-error@24:22 {{}} // expected_type_in_typealias
// expected-error@26:21 {{}} // expected_equal_in_typealias
// expected-error@28:21 {{}} // expected_equal_in_typealias
// expected-error@28:26 2 {{}} // expected_expr,statement_same_line_without_semi
// expected-error@32:23 {{}} // expected_type_in_typealias
// expected-error@34:11 {{}} // keyword_cant_be_identifier
// expected-note@34:11 {{}} // backticks_to_escape
// ---- end ASTGen parity ----
