// RUN; %target-typecheck-verify-swift

/* unterminated block comment expected_note{{comment started here}}
   expected_error{{unterminated '/*' comment}} {{60-60=*/}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/EOF/block-comment.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@3:1 {{}} // lex_comment_start
// expected-error@13:31 {{}} // lex_unterminated_block_comment
// ---- end ASTGen parity ----
