// RUN; %target-typecheck-verify-swift

/* outer block comment starts here expected_note{{comment started here}}
  /* inner block comment starts and ends here */
/* a second inner block started here
/* another inner block comment starts here
   Note that there are now three open comment blocks.
   The error message on the next line bumps that to four,
   then the fix-it text lowers that to two.
   expected_error{{unterminated '/*' comment}} {{62-62=*/*/}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/EOF/block-comment-nested.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@3:1 {{}} // lex_comment_start
// expected-error@19:31 {{}} // lex_unterminated_block_comment
// ---- end ASTGen parity ----
