// RUN; %target-typecheck-verify-swift

// This file does not end in a trailing newline; this is deliberate!
/* unterminated block comment expected_note{{comment started here}} expected_error{{unterminated '/*' comment}}{{126-126=*/}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/EOF/block-comment-missing-newline.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@4:1 {{}} // lex_comment_start
// expected-error@13:31 {{}} // lex_unterminated_block_comment
// ---- end ASTGen parity ----
