// RUN; %target-typecheck-verify-swift

func fuzz() { for var H
// expected_error@-1{{expected 'in' after for-each pattern}}
// expected_error@-2{{expected Sequence expression for for-each loop}}
// expected_error@-3{{expected '{' to start the body of for-each loop}}
// expected_note@-4 {{to match this opening '{'}}
// expected_error@+1{{expected '}' at end of brace statement}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/EOF/unfinished-for-at-eof.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@3:13 {{}} // opening_brace
// expected-error@3:24 3 {{}} // expected_foreach_container,expected_foreach_in,expected_foreach_lbrace
// expected-error@19:1 {{}} // expected_rbrace_in_brace_stmt
// ---- end ASTGen parity ----
