// RUN; %target-swift-frontend -typecheck -verify -module-name main %s

// Tests for interaction between comments & operators from SE-0037
// which defined comments to be whitespace for operator arity rules.

let foo: Bool! = true

// Used to be errors, should now work
let a = /* */!foo
_ = 1/**/+ 2
_ = 1 /**/+ 2
_ = 1 +/*hi*/2

// Used to work, should now be errors
// The actual error produced is probably not important.
// These are wrapped in functions to allow the parser to recover before the next test case.
func test1() { _ = foo/* */?.description }    // expected_error {{expected ':' after '? ...' in ternary expression}}
func test2() { _ = foo/* */! }                // expected_error {{expected expression after operator}}
func test3() { _ = 1/**/+2 }                  // expected_error {{consecutive statements on a line must be separated by ';'}} expected_warning {{result of operator '+' is unused}}
func test4() { _ = 1+/**/2 }                  // expected_error {{'+' is not a postfix unary operator}} expected_error {{consecutive statements on a line must be separated by ';'}} expected_warning {{integer literal is unused}}

// Continue to be errors
func test5() { _ = !/* */foo }                // expected_error {{unary operator cannot be separated from its operand}}
func test6() { _ = 1+/* */2 }                 // expected_error {{'+' is not a postfix unary operator}} expected_error {{consecutive statements on a line must be separated by ';'}} expected_warning {{integer literal is unused}}

// Continue to work
_ = foo!// this is dangerous
_ = 1 +/**/ 2
_ = 1 +/* hi */2

// Ensure built-in operators are properly tokenized.
_ =/**/2
_/**/= 2
typealias A = () ->/* */()
func test7(x: Int) { _ = x./* desc */ } // expected_error {{expected member name following '.'}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/comment_operator.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -module-name main %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@17:28 {{}} // expected_colon_after_ternary_question
// expected-error@18:30 {{}} // expected_expr_after_operator
// expected-error@19:21 {{}} // statement_same_line_without_semi
// expected-error@20:22 {{}} // statement_same_line_without_semi
// expected-error@23:20 {{}} // expected_prefix_operator
// expected-error@24:22 {{}} // statement_same_line_without_semi
// expected-error@35:27 {{}} // expected_member_name
// ---- end ASTGen parity ----
