// RUN; %target-typecheck-verify-swift \
// RUN;     -verify-additional-prefix enabled- \
// RUN;     -enable-experimental-feature CoroutineAccessors \
// RUN;     -debug-diagnostic-names
// RUN; %target-typecheck-verify-swift \
// RUN;     -verify-additional-prefix disabled- \
// RUN;     -debug-diagnostic-names

// REQUIRES; swift_feature_CoroutineAccessors

// Properties with implicit getters which call functions named modify.

func modify<T>(_ c : () -> T) -> T { c() }
func read<T>(_ c : () -> T) -> T { c() }

// enabled: need reader
// disabled: ok!
var im : Int {
  yielding mutate { // expected_error{{variable with a 'yielding mutate' accessor must also have a getter, addressor, or 'yielding borrow' accessor}}
                   // expected_disabled-error@-1{{accessor_requires_coroutine_accessor}}
    1 // expected_warning{{integer literal is unused}}
  }
}

// enabled: ok
// disabled: ok!
var ir : Int {
  yielding borrow { // expected_disabled-error{{accessor_requires_coroutine_accessor}}
    1 // expected_warning{{integer literal is unused}}
  }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/coroutine_accessors_ambiguity.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@19:12 {{}} // missing_reading_accessor
// expected-error@19:19 {{}} // accessor_requires_coroutine_accessors
// expected-error@28:19 {{}} // accessor_requires_coroutine_accessors
// ---- end ASTGen parity ----
