// RUN; not %target-swift-frontend -typecheck %s 2>&1 | %FileCheck --check-prefix=CHECK-WITHOUT %s 
// RUN; %target-typecheck-verify-swift -enable-experimental-static-assert
// RUN; %target-typecheck-verify-swift -enable-experimental-feature StaticAssert

// REQUIRES; swift_feature_StaticAssert

#if compiler(>=5.3) && $StaticAssert
#assert(true)
#else
// CHECK-WITHOUT: cannot find 'complete' in scope
complete junk
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/features.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@1:1 {{}} // parser_new_parser_errors
// expected-error@11:9 {{}} // bridged_error
// expected-note@11:9 2 {{}} // bridged_note
// ---- end ASTGen parity ----
