#!/usr/bin/swift // expected_error {{hashbang line is allowed only in the main file}}
class Foo {}
// Check that we diagnose and skip the hashbang at the beginning of the file
// when compiling in library mode.
// RUN; %target-typecheck-verify-swift -parse-as-library

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/hashbang_library.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-as-library %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@1:1 {{}} // lex_hashbang_not_allowed
// ---- end ASTGen parity ----
