// RUN; %target-typecheck-verify-swift -verify-ignore-unrelated

func my_print<T>(_ t: T) {}

class 你好 {
  class שלום {
    class வணக்கம் {
      class Γειά {
        class func привет() {
          my_print("hello")
        }
      }
    }
  }
}

你好.שלום.வணக்கம்.Γειά.привет()

// Identifiers cannot start with combining chars.
_ = .́duh() // expected_error {{cannot find operator '.́' in scope}} // expected_error{{cannot find 'duh' in scope}}

// Combining characters can be used within identifiers.
func s̈pin̈al_tap̈() {}

// Private-use characters aren't valid in Swift source.
() // expected_error{{invalid character in source file}} {{1-4= }}

// Placeholders are recognized as identifiers but with error.
func <#some name#>() {} // expected_error {{editor placeholder in source file}}

// Keywords as identifiers
class switch {} // expected_error {{keyword 'switch' cannot be used as an identifier here}} expected_note {{if this name is unavoidable, use backticks to escape it}} {{7-13=`switch`}}
struct Self {} // expected_error {{keyword 'Self' cannot be used as an identifier here}} expected_note {{if this name is unavoidable, use backticks to escape it}} {{8-12=`Self`}}
protocol enum {} // expected_error {{keyword 'enum' cannot be used as an identifier here}} expected_note {{if this name is unavoidable, use backticks to escape it}} {{10-14=`enum`}}
protocol test {
  associatedtype public // expected_error {{keyword 'public' cannot be used as an identifier here}} expected_note {{if this name is unavoidable, use backticks to escape it}} {{18-24=`public`}}
}
func _(_ x: Int) {} // expected_error {{keyword '_' cannot be used as an identifier here}} // expected_note {{if this name is unavoidable, use backticks to escape it}} {{6-7=`_`}}

// SIL keywords are tokenized as normal identifiers in non-SIL mode.
_ = undef // expected_error {{cannot find 'undef' in scope}}
_ = sil // expected_error {{cannot find 'sil' in scope}}
_ = sil_stage // expected_error {{cannot find 'sil_stage' in scope}}
_ = sil_vtable // expected_error {{cannot find 'sil_vtable' in scope}}
_ = sil_global // expected_error {{cannot find 'sil_global' in scope}}
_ = sil_witness_table // expected_error {{cannot find 'sil_witness_table' in scope}}
_ = sil_default_witness_table // expected_error {{cannot find 'sil_default_witness_table' in scope}}
_ = sil_coverage_map // expected_error {{cannot find 'sil_coverage_map' in scope}}
_ = sil_scope // expected_error {{cannot find 'sil_scope' in scope}}

// https://github.com/apple/swift/issues/57542
// Make sure we do not parse the '_' on the newline as being part of the 'variable' identifier on the line before.

@propertyWrapper 
struct Wrapper {
  var wrappedValue = 0
}

func localScope() {
  @Wrapper var variable
  _ = 0
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/identifiers.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@26:1 {{}} // lex_invalid_character
// expected-error@29:6 {{}} // lex_editor_placeholder
// expected-error@32:7 {{}} // keyword_cant_be_identifier
// expected-note@32:7 {{}} // backticks_to_escape
// expected-error@33:8 {{}} // keyword_cant_be_identifier
// expected-note@33:8 {{}} // backticks_to_escape
// expected-error@34:10 {{}} // keyword_cant_be_identifier
// expected-note@34:10 {{}} // backticks_to_escape
// expected-error@36:18 {{}} // keyword_cant_be_identifier
// expected-note@36:18 {{}} // backticks_to_escape
// expected-error@38:6 {{}} // keyword_cant_be_identifier
// expected-note@38:6 {{}} // backticks_to_escape
// ---- end ASTGen parity ----
