// RUN; %target-typecheck-verify-swift

var êx = "" // expected_error{{invalid UTF-8 found in source file}} {{5-6= }} 

// Make sure we don't stop processing the whole file.
static func foo() {} // expected_error{{static methods may only be declared on a type}} {{1-8=}}

// UTF-8 RFC 2279: The octet values FE and FF never appear.
// UTF-8 RFC 3629: The octet values C0, C1, F5 to FF never appear.
// Below this line are such octets that should be skipped by the lexer.
// They may not be rendered correctly by your text editor, if at all.

// Begin magic UTF-8 values
// 0xC0
¿ // expected_error {{invalid UTF-8 found in source file}}
// 0xC1
¡ // expected_error {{invalid UTF-8 found in source file}}
// 0xF5
ı // expected_error {{invalid UTF-8 found in source file}}
// 0xF6
ˆ // expected_error {{invalid UTF-8 found in source file}}
// 0xF7
˜ // expected_error {{invalid UTF-8 found in source file}}
// 0xF8
¯ // expected_error {{invalid UTF-8 found in source file}}
// 0xF9
˘ // expected_error {{invalid UTF-8 found in source file}}
// 0xFB
˚ // expected_error {{invalid UTF-8 found in source file}}
// 0xFC
¸ // expected_error {{invalid UTF-8 found in source file}}
// 0xFD
˝ // expected_error {{invalid UTF-8 found in source file}}
// End magic UTF-8 values

// Make sure we don't stop processing the whole file.
static func bar() {} // expected_error{{static methods may only be declared on a type}} {{1-8=}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/invalid-utf8.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@3:5 {{}} // lex_invalid_utf8
// expected-error@6:8 {{}} // static_func_decl_global_scope
// expected-error@15:1 {{}} // lex_invalid_utf8
// expected-error@17:1 {{}} // lex_invalid_utf8
// expected-error@19:1 {{}} // lex_invalid_utf8
// expected-error@21:1 {{}} // lex_invalid_utf8
// expected-error@23:1 {{}} // lex_invalid_utf8
// expected-error@25:1 {{}} // lex_invalid_utf8
// expected-error@27:1 {{}} // lex_invalid_utf8
// expected-error@29:1 {{}} // lex_invalid_utf8
// expected-error@31:1 {{}} // lex_invalid_utf8
// expected-error@33:1 {{}} // lex_invalid_utf8
// expected-error@37:8 {{}} // static_func_decl_global_scope
// ---- end ASTGen parity ----
