// RUN; %target-typecheck-verify-swift -target %target-swift-6.0-abi-triple

typealias FnType = @isolated(any) () -> ()

func testInParameter(function: @isolated(any) () -> ()) {}

func testLookahead() {
  let array = [@isolated(any) () -> ()]()
  _ = array
}

func testInvalidIsolation(_ x: @isolated(foo) () -> Void) {}
// expected_error@-1 {{expected 'any' as the isolation kind}} {{42-45=any}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/isolated_any.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -target %target-swift-6.0-abi-triple %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@12:42 {{}} // attr_isolated_expected_kind
// ---- end ASTGen parity ----
