// RUN; %target-typecheck-verify-swift -enable-experimental-move-only

// Temporary `_move` syntax is still parsed but raises a warning and fixit.
func oldMoveSyntax(x: String) {
  _ = _move x // expected_warning{{renamed to 'consume'}} {{7-12=consume}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/move_expr_legacy.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-move-only %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-warning@5:13 {{}} // move_consume_final_spelling
// ---- end ASTGen parity ----
