// RUN; not %target-typecheck-verify-swift

#error("""

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/multiline_pound_diagnostic_arg_rdar_41154797.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@3:8 2 {{}} // lex_unterminated_string,pound_diagnostic_expected_string
// ---- end ASTGen parity ----
