// RUN; %target-typecheck-verify-swift

// Per rdar://problem/32316666 , it is a common mistake for beginners
// to start a function name with a number, so it's worth
// special-casing the diagnostic to make it clearer.

func 1() {}
// expected_error@-1 {{function name can only start with a letter or underscore, not a number}}
func 2.0() {}
// expected_error@-1 {{function name can only start with a letter or underscore, not a number}}
func 3func() {}
// expected_error@-1 {{function name can only start with a letter or underscore, not a number}}
// expected_error@-2 {{'f' is not a valid digit in integer literal}}

protocol 4 {
  // expected_error@-1 {{protocol name can only start with a letter or underscore, not a number}}
  associatedtype 5
  // expected_error@-1 {{associatedtype name can only start with a letter or underscore, not a number}}
}
protocol 6.0 {
  // expected_error@-1 {{protocol name can only start with a letter or underscore, not a number}}
  associatedtype 7.0
  // expected_error@-1 {{associatedtype name can only start with a letter or underscore, not a number}}
}
protocol 8protocol {
  // expected_error@-1 {{protocol name can only start with a letter or underscore, not a number}}
  // expected_error@-2 {{'p' is not a valid digit in integer literal}}
  associatedtype 9associatedtype
  // expected_error@-1 {{associatedtype name can only start with a letter or underscore, not a number}}
  // expected_error@-2 {{'a' is not a valid digit in integer literal}}
}

typealias 10 = Int
// expected_error@-1 {{typealias name can only start with a letter or underscore, not a number}}
typealias 11.0 = Int
// expected_error@-1 {{typealias name can only start with a letter or underscore, not a number}}
typealias 12typealias = Int
// expected_error@-1 {{typealias name can only start with a letter or underscore, not a number}}
// expected_error@-2 {{'t' is not a valid digit in integer literal}}

struct 13 {}
// expected_error@-1 {{struct name can only start with a letter or underscore, not a number}}
struct 14.0 {}
// expected_error@-1 {{struct name can only start with a letter or underscore, not a number}}
struct 15struct {}
// expected_error@-1 {{struct name can only start with a letter or underscore, not a number}}
// expected_error@-2 {{'s' is not a valid digit in integer literal}}

enum 16 {}
// expected_error@-1 {{enum name can only start with a letter or underscore, not a number}}
enum 17.0 {}
// expected_error@-1 {{enum name can only start with a letter or underscore, not a number}}
enum 18enum {}
// expected_error@-1 {{enum name can only start with a letter or underscore, not a number}}
// expected_error@-2 {{'n' is not a valid digit in floating point exponent}}

class 19 {
  // expected_error@-1 {{class name can only start with a letter or underscore, not a number}}
  func 20() {}
  // expected_error@-1 {{function name can only start with a letter or underscore, not a number}}
}
class 21.0 {
  // expected_error@-1 {{class name can only start with a letter or underscore, not a number}}
  func 22.0() {}
  // expected_error@-1 {{function name can only start with a letter or underscore, not a number}}
}

class 23class {
  // expected_error@-1 {{class name can only start with a letter or underscore, not a number}}
  // expected_error@-2 {{'c' is not a valid digit in integer literal}}
  func 24method() {}
  // expected_error@-1 {{function name can only start with a letter or underscore, not a number}}
  // expected_error@-2 {{'m' is not a valid digit in integer literal}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/number_identifier_errors.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@7:6 {{}} // number_cant_start_decl_name
// expected-error@9:6 {{}} // number_cant_start_decl_name
// expected-error@11:6 {{}} // number_cant_start_decl_name
// expected-error@11:7 {{}} // lex_invalid_digit_in_int_literal
// expected-error@15:10 {{}} // number_cant_start_decl_name
// expected-error@17:18 {{}} // number_cant_start_decl_name
// expected-error@20:10 {{}} // number_cant_start_decl_name
// expected-error@22:18 {{}} // number_cant_start_decl_name
// expected-error@25:10 {{}} // number_cant_start_decl_name
// expected-error@25:11 {{}} // lex_invalid_digit_in_int_literal
// expected-error@28:18 {{}} // number_cant_start_decl_name
// expected-error@28:19 {{}} // lex_invalid_digit_in_int_literal
// expected-error@33:11 {{}} // number_cant_start_decl_name
// expected-error@35:11 {{}} // number_cant_start_decl_name
// expected-error@37:11 {{}} // number_cant_start_decl_name
// expected-error@37:13 {{}} // lex_invalid_digit_in_int_literal
// expected-error@41:8 {{}} // number_cant_start_decl_name
// expected-error@43:8 {{}} // number_cant_start_decl_name
// expected-error@45:8 {{}} // number_cant_start_decl_name
// expected-error@45:10 {{}} // lex_invalid_digit_in_int_literal
// expected-error@49:6 {{}} // number_cant_start_decl_name
// expected-error@51:6 {{}} // number_cant_start_decl_name
// expected-error@53:6 {{}} // number_cant_start_decl_name
// expected-error@53:9 {{}} // lex_invalid_digit_in_fp_exponent
// expected-error@57:7 {{}} // number_cant_start_decl_name
// expected-error@59:8 {{}} // number_cant_start_decl_name
// expected-error@62:7 {{}} // number_cant_start_decl_name
// expected-error@64:8 {{}} // number_cant_start_decl_name
// expected-error@68:7 {{}} // number_cant_start_decl_name
// expected-error@68:9 {{}} // lex_invalid_digit_in_int_literal
// expected-error@71:8 {{}} // number_cant_start_decl_name
// expected-error@71:10 {{}} // lex_invalid_digit_in_int_literal
// ---- end ASTGen parity ----
