// RUN; %target-typecheck-verify-swift

struct A {
  func foo() {}
}

var a : A?
var b : A ? // expected_error {{consecutive statements on a line}} {{10-10=;}} expected_error {{expected expression}}

var c = a?  // expected_error {{'?' must be followed by a call, member lookup, or subscript}}
var d : ()? = a?.foo()

var e : (() -> A)?
var f = e?()

struct B<T> {}
var g = B<A?>()
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/optional.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@8:10 {{}} // statement_same_line_without_semi
// expected-error@8:11 {{}} // expected_expr
// ---- end ASTGen parity ----
