// RUN; %target-swift-frontend -typecheck -verify %s

struct Payload: ~Copyable {
    var x: Int
    var y: String
}

enum Foo: ~Copyable {
    case payload(Payload)
    case noPayload
}

enum Bar: ~Copyable {
    case payload(Foo)
    case noPayload

    var member: Bar { fatalError() }
}

struct SourceBreakTest {
    func foo() -> Bar {}

    func callAsFunction() -> Bar { fatalError() }
}

let borrowing = SourceBreakTest()

func ~=(_: borrowing Bar, _: borrowing Bar) -> Bool { fatalError() }

func useBorrowBar(_: borrowing Bar) { fatalError() }
func useBorrowFoo(_: borrowing Foo) { fatalError() }
func useBorrowPayload(_: borrowing Payload) { fatalError() }

func testBorrowingPatterns(bar: borrowing Bar) {
    switch bar {
    case borrowing .foo(): // parses as `borrowing.foo()` as before
        break
    case borrowing (): // parses as `borrowing()` as before
        break

    case borrowing x: // expected_warning{{'borrowing' in pattern matches is deprecated}} {{10-19=let}}
        useBorrowBar(x)

    case .payload(borrowing x): // expected_warning{{'borrowing' in pattern matches is deprecated}} {{19-28=let}}
        useBorrowFoo(x)

    case borrowing x.member: // expected_warning{{deprecated}} expected_error{{'borrowing' pattern modifier must be directly applied to pattern variable name}} expected_error{{cannot find 'x' in scope}}
        break

    case borrowing x: // expected_warning{{'borrowing' in pattern matches is deprecated}} {{10-19=let}}
        useBorrowBar(x)

    case _borrowing x: // expected_warning{{'borrowing' in pattern matches is deprecated}} {{10-20=let}}
        useBorrowBar(x)

    default:
        break
    }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/pattern_borrow_bindings.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-warning@41:10 {{}} // borrowing_syntax_change
// expected-warning@44:19 {{}} // borrowing_syntax_change
// expected-warning@47:10 {{}} // borrowing_syntax_change
// expected-error@47:20 {{}} // borrowing_subpattern_unsupported
// expected-warning@50:10 {{}} // borrowing_syntax_change
// expected-warning@53:10 {{}} // borrowing_syntax_change
// ---- end ASTGen parity ----
