// RUN; %target-typecheck-verify-swift -parse-as-library

//===--- Recovery for extra braces at top level.
//===--- Keep this test the first one in the file.

// Check that we handle multiple consecutive right braces.
} // expected_error{{extraneous '}' at top level}} {{1-3=}}
} // expected_error{{extraneous '}' at top level}} {{1-3=}}

func foo() {}
// Check that we handle multiple consecutive right braces.
} // expected_error{{extraneous '}' at top level}} {{1-3=}}
} // expected_error{{extraneous '}' at top level}} {{1-3=}}
func bar() {}

//===--- Recovery for extra braces at top level.
//===--- Keep this test the last one in the file.

// Check that we handle multiple consecutive right braces.
} // expected_error{{extraneous '}' at top level}} {{1-3=}}
} // expected_error{{extraneous '}' at top level}} {{1-3=}}

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/recovery_library.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-as-library %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@7:1 {{}} // extra_rbrace
// expected-error@8:1 {{}} // extra_rbrace
// expected-error@12:1 {{}} // extra_rbrace
// expected-error@13:1 {{}} // extra_rbrace
// expected-error@20:1 {{}} // extra_rbrace
// expected-error@21:1 {{}} // extra_rbrace
// ---- end ASTGen parity ----
