// RUN; %target-typecheck-verify-swift -target %target-swift-5.1-abi-triple -enable-experimental-feature SendingArgsAndResults -strict-concurrency=complete

// REQUIRES; swift_feature_SendingArgsAndResults

func testArg(_ x: sending String) {
}

func testResult() -> sending String {
  ""
}

func testArgResult(_ x: sending String) -> sending String {
}

func testVarDeclDoesntWork() {
  var x: sending String // expected_error {{'sending' may only be used on parameters and results}}
  let y: sending String // expected_error {{'sending' may only be used on parameters and results}}

  struct S {
    var opaqueStored: sending some Equatable = 0 // expected_error {{'sending' may only be used on parameters and results}}
    let opaqueStoredImmutable: sending some Equatable = 0 // expected_error {{'sending' may only be used on parameters and results}}
    var opaqueComputed: sending some Equatable { 0 } // expected_error {{'sending' may only be used on parameters and results}}
    var opaqueWriteback: sending some Equatable { // expected_error {{'sending' may only be used on parameters and results}}
      get { 0 }
      set {}
    }
  }
}

func testVarDeclTupleElt() -> (sending String, String) {} // expected_error {{'sending' cannot be applied to tuple elements}}

func testVarDeclTuple2(_ x: (sending String)) {}
func testVarDeclTuple2(_ x: (sending String, String)) {} // expected_error {{'sending' cannot be applied to tuple elements}}

func testArgWithConsumingWrongOrder(_ x: sending consuming String, _ y: sending inout String) {}
// expected_error @-1 {{'sending' must be placed after specifier 'consuming'}}
// expected_error @-2 {{'sending' must be placed after specifier 'inout'}}

func testArgWithConsumingWrongOrderType(_ x: (sending consuming String, sending inout String) -> ()) {}
// expected_error @-1 {{'sending' must be placed after specifier 'consuming'}}
// expected_error @-2 {{'sending' must be placed after specifier 'inout'}}

func testBorrowSending(_ x: borrowing sending String) {}
// expected_error @-1 {{'sending' cannot be used together with 'borrowing'}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/sending.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -target %target-swift-5.1-abi-triple -enable-experimental-feature SendingArgsAndResults -strict-concurrency=complete %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: swift_feature_SendingArgsAndResults
// XFAIL: *
// expected-error@35:50 {{}} // sending_before_parameter_specifier
// expected-error@35:81 {{}} // sending_before_parameter_specifier
// expected-error@39:55 {{}} // sending_before_parameter_specifier
// expected-error@39:81 {{}} // sending_before_parameter_specifier
// expected-error@43:39 {{}} // sending_cannot_be_used_with_borrowing
// ---- end ASTGen parity ----
