// RUN; %target-typecheck-verify-swift \
// RUN;  -enable-experimental-feature CustomAvailability \
// RUN;  -define-enabled-availability-domain EnabledDomain \
// RUN;  -define-disabled-availability-domain DisabledDomain \
// RUN;  -define-dynamic-availability-domain DynamicDomain

// REQUIRES; swift_feature_CustomAvailability

if #available(EnabledDomain) { }
if #available(DisabledDomain) { }
if #available(DynamicDomain) { }
if #available(UnknownDomain) { } // expected_error {{cannot find availability domain 'UnknownDomain'}}
// expected_error@-1 {{condition required for target platform}}

if #unavailable(EnabledDomain) { }
if #unavailable(DisabledDomain) { }
if #unavailable(DynamicDomain) { }
if #unavailable(UnknownDomain) { } // expected_error {{cannot find availability domain 'UnknownDomain'}}

if #available(EnabledDomain 1.0) { } // expected_error {{unexpected version number for EnabledDomain}}
if #available(EnabledDomain, DisabledDomain) { } // expected_error {{EnabledDomain availability must be specified alone}}

if #available(EnabledDomain, swift 5) { } // expected_error {{EnabledDomain availability must be specified alone}}

while #available(EnabledDomain) { }

guard #available(EnabledDomain) else { }
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/availability_query_custom_domains.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-feature CustomAvailability -define-enabled-availability-domain EnabledDomain -define-disabled-availability-domain DisabledDomain -define-dynamic-availability-domain DynamicDomain %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_CustomAvailability
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// ---- end ASTGen parity ----
