// RUN; %target-typecheck-verify-swift -verify-ignore-unrelated

// expected_error @+4 {{type annotation missing in pattern}}
// expected_error @+3 {{cannot find operator '⁚' in scope}}
// expected_error @+2 {{operator with postfix spacing cannot start a subexpression}}
// expected_error @+1 {{consecutive statements on a line must be separated by ';'}}
let number⁚ Int // expected_note {{operator '⁚' (Two Dot Punctuation) looks similar to ':' (Colon); did you mean ':' (Colon)?}} {{11-14=:}}

// expected_warning @+3 2 {{integer literal is unused}}
// expected_error @+2 {{invalid character in source file}}
// expected_error @+1 {{consecutive statements on a line must be separated by ';'}}
5 ‒ 5 // expected_note {{unicode character '‒' (Figure Dash) looks similar to '-' (Hyphen Minus); did you mean to use '-' (Hyphen Minus)?}} {{3-6=-}}

// expected_error @+3 {{cannot convert value of type '(Bool, _)' to expected condition type 'Bool'}}
// expected_error @+2 {{cannot find 'ꝸꝸꝸ' in scope}}
// expected_error @+1 {{expected ',' separator}}
if (true ꝸꝸꝸ false) {} // expected_note {{identifier 'ꝸꝸꝸ' contains possibly confused characters; did you mean to use '&&&'?}} {{10-19=&&&}}

// expected_error @+3 {{invalid character in source file}}
// expected_error @+2 {{expected ',' separator}}
// expected_error @+1 {{binary operator '==' cannot be applied to operands of type '(Int, Int)' and 'Int'}}
if (5 ‒ 5) == 0 {} // expected_note {{unicode character '‒' (Figure Dash) looks similar to '-' (Hyphen Minus); did you mean to use '-' (Hyphen Minus)?}} {{7-10=-}}

// GREEK QUESTION MARK (which looks like a semicolon) 
print("A"); print("B")
// expected_error@-1 2{{consecutive statements on a line must be separated by ';'}}
// expected_error@-2 {{cannot find ';' in scope}}
// expected_note@-3 {{identifier ';' (Greek Question Mark) looks similar to ';' (Semicolon); did you mean ';' (Semicolon)?}} {{11-13=;}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/confusables.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@7:11 2 {{}} // invalid_postfix_operator,statement_same_line_without_semi
// expected-error@12:2 {{}} // statement_same_line_without_semi
// expected-error@12:3 {{}} // lex_invalid_character
// expected-note@12:3 {{}} // lex_confusable_character
// expected-error@17:10 {{}} // expected_separator
// expected-error@22:7 {{}} // lex_invalid_character
// expected-note@22:7 {{}} // lex_confusable_character
// expected-error@22:11 {{}} // expected_separator
// expected-error@25:11 {{}} // statement_same_line_without_semi
// expected-error@25:13 {{}} // statement_same_line_without_semi
// ---- end ASTGen parity ----
