// RUN; %target-typecheck-verify-swift

// https://github.com/apple/swift/issues/44070

class X {}
func foo() {}

let a:[X]()  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= = }}
let b: [X]()  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= =}}
let c :[X]()  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{7-8== }}
let d : [X]()  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{7-8==}}

let e: X(), ee: Int  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= =}}

let f:/*comment*/[X]()  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= = }}

var _1 = 1, _2 = 2

// paren follows the type, but it's part of a separate (valid) expression
let ff: X
(_1, _2) = (_2, _1)
let fff: X
 (_1, _2) = (_2, _1)

let g: X(x)  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= =}}
let h: X(x, y)  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= =}}
let i: X() { foo() }  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= =}}
let j: X(x) { foo() }  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= =}}
let k: X(x, y) { foo() }  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{6-7= =}}

func nonTopLevel() {
  let a:[X]()   // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{8-9= = }}
  let i: X() { foo() }  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{8-9= =}}
  let j: X(x) { foo() }  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{8-9= =}}
  let k: X(x, y) { foo() }  // expected_error{{unexpected initializer in pattern; did you mean to use '='?}} {{8-9= =}}
  _ = (a, i, j, k)
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnose_initializer_as_typed_pattern.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@8:10 {{}} // initializer_as_typed_pattern
// expected-error@9:11 {{}} // initializer_as_typed_pattern
// expected-error@10:11 {{}} // initializer_as_typed_pattern
// expected-error@11:12 {{}} // initializer_as_typed_pattern
// expected-error@13:9 {{}} // initializer_as_typed_pattern
// expected-error@15:21 {{}} // initializer_as_typed_pattern
// expected-error@25:9 {{}} // initializer_as_typed_pattern
// expected-error@26:9 {{}} // initializer_as_typed_pattern
// expected-error@27:9 {{}} // initializer_as_typed_pattern
// expected-error@28:9 {{}} // initializer_as_typed_pattern
// expected-error@29:9 {{}} // initializer_as_typed_pattern
// expected-error@32:12 {{}} // initializer_as_typed_pattern
// expected-error@33:11 {{}} // initializer_as_typed_pattern
// expected-error@34:11 {{}} // initializer_as_typed_pattern
// expected-error@35:11 {{}} // initializer_as_typed_pattern
// ---- end ASTGen parity ----
