// RUN; %target-swift-frontend -parse -verify %s

func test1() {
  @s
  return // expected_error {{expected declaration}}
}
func test2() {
  @unknown // expected_error {{unknown attribute 'unknown'}}
  return // expected_error {{expected declaration}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/fixed_infinite_loops.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@5:3 {{}} // expected_decl
// expected-error@8:4 {{}} // unknown_attr_name
// expected-error@9:3 {{}} // expected_decl
// ---- end ASTGen parity ----
