// RUN; %target-typecheck-verify-swift

struct IntRange<Int> : Sequence, IteratorProtocol {
  typealias Element = (Int, Int)
  func next() -> (Int, Int)? {}

  typealias Iterator = IntRange<Int>
  func makeIterator() -> IntRange<Int> { return self }
}

func for_each(r: Range<Int>, iir: IntRange<Int>) { // expected_note {{'r' declared here}}
  var sum = 0

  // Simple foreach loop, using the variable in the body
  for i in r {
    sum = sum + i
  }
  // Check scoping of variable introduced with foreach loop
  i = 0 // expected_error{{cannot find 'i' in scope; did you mean 'r'?}}

  // For-each loops with two variables and varying degrees of typedness
  for (i, j) in iir {
    sum = sum + i + j
  }
  for (i, j) in iir {
    sum = sum + i + j
  }
  for (i, j) : (Int, Int) in iir {
    sum = sum + i + j
  }

  // Parse errors
  // FIXME: Bad diagnostics; should be just 'expected 'in' after for-each patter'.
  for i r { // expected_error {{found an unexpected second identifier in constant declaration}}
  }         // expected_note @-1 {{join the identifiers together}}
            // expected_note @-2 {{join the identifiers together with camel-case}}
            // expected_error @-3 {{expected 'in' after for-each pattern}}
            // expected_error @-4 {{expected Sequence expression for for-each loop}}
  for i in r sum = sum + i; // expected_error{{expected '{' to start the body of for-each loop}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/foreach.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@34:9 {{}} // repeated_identifier
// expected-note@34:9 2 {{}} // join_identifiers,join_identifiers_camel_case
// expected-error@34:11 2 {{}} // expected_foreach_container,expected_foreach_in
// expected-error@39:14 {{}} // expected_foreach_lbrace
// ---- end ASTGen parity ----
