// RUN; %target-typecheck-verify-swift

func noConditionNoElse() {
  guard {} // expected_error {{missing condition in 'guard' statement}} expected_error {{expected 'else' after 'guard' condition}}
}
func noCondition() {
  guard else {} // expected_error {{missing condition in 'guard' statement}} 
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/guard.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:3 {{}} // missing_condition_after_guard
// expected-error@4:9 {{}} // expected_else_after_guard
// expected-error@7:3 {{}} // missing_condition_after_guard
// ---- end ASTGen parity ----
