// RUN; %target-typecheck-verify-swift
// REQUIRES; concurrency

@available(SwiftStdlib 5.1, *)
actor MyActor {}

class MyClass {}

// Lifetime specifiers before parameter names were disallowed in Swift 3 (SE-0031).
// `isolated`, `sending` and `_const` got added after Swift 3 without a diagnostic 
// to disallow them before parameter names.

func foo(inout x b: MyClass) {} // expected_error {{'inout' before a parameter name is not allowed, place it before the parameter type instead}}

func foo(borrowing x b: MyClass) {} // expected_error {{'borrowing' before a parameter name is not allowed, place it before the parameter type instead}}

@available(SwiftStdlib 5.1, *)
func foo(isolated x b: MyActor) {} // expected_warning {{'isolated' before a parameter name is not allowed, place it before the parameter type instead; this is an error in the Swift 6 language mode}}

func foo(_const x b: MyClass) {} // expected_warning {{'_const' before a parameter name is not allowed, place it before the parameter type instead; this is an error in the Swift 6 language mode}}

@available(SwiftStdlib 5.1, *)
func foo(sending x b: MyActor) {} // expected_warning {{'sending' before a parameter name is not allowed, place it before the parameter type instead}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/parameter_specifier_before_param_name.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: concurrency
// XFAIL: *
// expected-error@13:10 {{}} // parameter_specifier_as_attr_disallowed
// expected-error@15:10 {{}} // parameter_specifier_as_attr_disallowed
// expected-warning@18:10 {{}} // parameter_specifier_as_attr_disallowed
// expected-warning@20:10 {{}} // parameter_specifier_as_attr_disallowed
// expected-warning@23:10 {{}} // parameter_specifier_as_attr_disallowed
// ---- end ASTGen parity ----
