// RUN; %target-typecheck-verify-swift

let _ = "foo\(#"bar"##)baz"
// expected_error@-1{{too many '#' characters in closing delimiter}}
// expected_error@-2{{expected ',' separator}}
// expected_error@-3{{expected a macro identifier}}

let _ = #"\##("invalid")"#
// expected_error@-1{{too many '#' characters in delimited escape}}
// expected_error@-2{{invalid escape sequence in literal}}

let _ = ###"""invalid"######
// expected_error@-1{{too many '#' characters in closing delimiter}}{{26-29=}}
// expected_error@-2{{consecutive statements on a line must be separated by ';'}}
// expected_error@-3{{expected a macro identifier}}

let _ = ####"invalid"###
// expected_error@-1{{unterminated string literal}}

let _ = ###"invalid"######
// expected_error@-1{{too many '#' characters in closing delimiter}}{{24-27=}}
// expected_error@-2{{consecutive statements on a line must be separated by ';'}}
// expected_error@-3{{expected a macro identifier}}

let _ = ##"""aa
  foobar
  aa"""##
// expected_error@-3{{multi-line string literal content must begin on a new line}}{{14-14=\n}}
// expected_error@-2{{multi-line string literal closing delimiter must begin on a new line}}{{5-5=\n}}

let _ = #""" foo "bar" #baz
  """#
// expected_error@-2{{multi-line string literal content must begin on a new line}}{{13-13=\n}}

let _ = ###""" "# "##
  """###
// expected_error@-2{{multi-line string literal content must begin on a new line}}{{15-15=\n}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/raw_string_errors.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@3:22 2 {{}} // expected_separator,lex_invalid_closing_delimiter
// expected-error@3:23 {{}} // macro_expansion_expr_expected_macro_identifier
// expected-error@8:13 2 {{}} // lex_invalid_escape,lex_invalid_escape_delimiter
// expected-error@12:26 2 {{}} // lex_invalid_closing_delimiter,statement_same_line_without_semi
// expected-error@12:27 {{}} // macro_expansion_expr_expected_macro_identifier
// expected-error@17:9 {{}} // lex_unterminated_string
// expected-error@20:24 2 {{}} // lex_invalid_closing_delimiter,statement_same_line_without_semi
// expected-error@20:25 {{}} // macro_expansion_expr_expected_macro_identifier
// expected-error@25:14 {{}} // lex_illegal_multiline_string_start
// expected-error@27:5 {{}} // lex_illegal_multiline_string_end
// expected-error@31:13 {{}} // lex_illegal_multiline_string_start
// expected-error@35:15 {{}} // lex_illegal_multiline_string_start
// ---- end ASTGen parity ----
