// RUN; %target-typecheck-verify-swift -parse-as-library

let x = 42
x + x; // expected_error {{expressions are not allowed at the top level}} expected_warning {{result of operator '+' is unused}}
x + x; // expected_error {{expressions are not allowed at the top level}} expected_warning {{result of operator '+' is unused}}
// Make sure we don't crash on closures at the top level
({ }) // expected_error {{expressions are not allowed at the top level}} expected_error{{function is unused}}
({ 5 }()) // expected_error {{expressions are not allowed at the top level}}
// expected_warning @-1 {{result of call to closure returning 'Int' is unused}}


// expected_error @+3 {{expected 'in' after for-each pattern}}
// expected_error @+2 {{expected Sequence expression for for-each loop}}
// expected_error @+1 {{expected '{' to start the body of for-each loop}}
for i
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/toplevel_library_invalid.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-as-library %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:1 {{}} // illegal_top_level_expr
// expected-error@5:1 {{}} // illegal_top_level_expr
// expected-error@7:1 {{}} // illegal_top_level_expr
// expected-error@8:1 {{}} // illegal_top_level_expr
// expected-error@15:6 3 {{}} // expected_foreach_container,expected_foreach_in,expected_foreach_lbrace
// ---- end ASTGen parity ----
