// RUN; %target-typecheck-verify-swift -swift-version 5 -module-name test

// Parsing support for typed throws.

enum MyError: Error {
  case epicFail
}

func specificThrowingFunc() throws(MyError) { }
func anyThrowingFunc() throws(any Error) { }

struct SomeStruct {
  init() throws(MyError) { }
}

typealias ThrowingFuncType = () throws(MyError) -> Void

func testClosures() {
  let _ = { () throws(MyError) in print("hello") }
  let _ = { (x: Int, y: Int) throws(MyError) -> Int in x + y }
}

@available(SwiftStdlib 6.0, *)
func testTypes() {
  let _ = [(Int, Int) throws(MyError) -> Int]()
}

func testMissingError() throws() { }
// expected_error@-1{{expected thrown error type after 'throws('}}

func testRethrowsWithThrownType() rethrows(MyError) { }
// expected_error@-1{{'rethrows' cannot be combined with a specific thrown error type}}

struct S<Element, Failure: Error> {
  init(produce: @escaping () async throws(Failure) -> Element?) {
  }
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/typed_throws.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 5 -module-name test %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@28:32 {{}} // expected_thrown_error_type
// expected-error@31:35 {{}} // rethrows_with_thrown_error
// ---- end ASTGen parity ----
