// RUN; %target-typecheck-verify-swift

let mid = "pete"

_ = "mid == \(pete" 
// expected_error @-1 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error @-2 {{unterminated string literal}}

let theGoat = "kanye \("
// expected_error @-1 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error @-2 {{unterminated string literal}}

let equation1 = "2 + 2 = \(2 + 2" 
// expected_error @-1 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error @-2 {{unterminated string literal}}

let s = "\(x"; print(x) 
// expected_error @-1 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error @-2 {{unterminated string literal}}

let zzz = "\(x; print(x)
// expected_error @-1 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error @-2 {{unterminated string literal}}

let goatedAlbum = "The Life Of \("Pablo"
// expected_error @-1 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error @-2 {{unterminated string literal}}

// expected_error @+3 {{cannot find ')' to match opening '(' in string interpolation}}
// expected_error @+1 {{unterminated string literal}}
_ = """
\(
"""
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/unclosed-string-interpolation.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@5:5 {{}} // lex_unterminated_string
// expected-error@5:14 {{}} // string_interpolation_unclosed
// expected-error@9:15 {{}} // lex_unterminated_string
// expected-error@9:23 {{}} // string_interpolation_unclosed
// expected-error@13:17 {{}} // lex_unterminated_string
// expected-error@13:27 {{}} // string_interpolation_unclosed
// expected-error@17:9 {{}} // lex_unterminated_string
// expected-error@17:11 {{}} // string_interpolation_unclosed
// expected-error@21:11 {{}} // lex_unterminated_string
// expected-error@21:13 {{}} // string_interpolation_unclosed
// expected-error@25:19 {{}} // lex_unterminated_string
// expected-error@25:33 {{}} // string_interpolation_unclosed
// expected-error@31:5 {{}} // lex_unterminated_string
// expected-error@32:2 {{}} // string_interpolation_unclosed
// ---- end ASTGen parity ----
