// RUN; %swift -typecheck %s -verify -target avr-none-none -disable-objc-interop -parse-stdlib

// expected_warning@<unknown> * {{no target microcontroller specified, please pass -mmcu=<mcu name>}}

#if arch(avr) && os(none) && _runtime(_Native) && _endian(little) && _pointerBitWidth(_16)
class C {}
var x = C()
#endif
var y = x

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/avrTarget.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -target avr-none-none -disable-objc-interop -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-warning@<unknown> {{}} // warning_from_clang
// ---- end ASTGen parity ----
