// RUN; %target-typecheck-verify-swift


#if DEBUG

#endif ; // expected_error {{extra tokens following conditional compilation directive}}

// <rdar://problem/17569958> #endif not parsed correctly when occurs as last line in file
#if DEBUG
func debug(msg: String) {
    print(msg)
}
#else
func debug(msg: String) {
}
// last line of file - make sure no \n sneaks in below #endif.
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/endif-on-end-of-file.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-error@6:8 {{}} // extra_tokens_conditional_compilation_directive
// ---- end ASTGen parity ----
