// RUN; %target-typecheck-verify-swift -swift-version 4.2

#if swift(>=4)
  let w = 1
#else
  // This shouldn't emit any diagnostics.
  asdf asdf asdf asdf
#endif

#if swift(>=4.0)
  let x = 1
#else
  // This shouldn't emit any diagnostics.
  asdf asdf asdf asdf
#endif

#if swift(>=4.0.0)
  let y = 1
#else
  // This shouldn't emit any diagnostics.
  asdf asdf asdf asdf
#endif

// NOTE: Please modify this condition...
#if swift(>=4.2)
  let b = 1
#else
  // This shouldn't emit any diagnostics.
  asdf asdf asdf asdf
#endif

// NOTE: ...and modify this condition...
#if swift(>=4.2.1)
  // This shouldn't emit any diagnostics.
  asdf asdf asdf asdf
#else
  let c = 1
#endif
// NOTE: ...the next time the version goes up.
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/language_version_explicit.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4.2 %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
