// RUN; %target-typecheck-verify-swift -parse-as-library

#if FAIL
class C {}

func > (lhs: C, rhs: C) -> Bool {
  return false
}
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/module_top_level.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -parse-as-library %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
