// RUN; %swift -typecheck %s -verify -target arm64-apple-none-macho -parse-stdlib
// RUN; %swift-ide-test -test-input-complete -source-filename=%s -target arm64-apple-none-macho

#if !_runtime(_multithreaded)
  func underNoThreads() {
    foo() // expected_error {{cannot find 'foo' in scope}}
  }
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/noneOSTarget.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -target arm64-apple-none-macho -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
