// RUN; %target-typecheck-verify-swift

// https://github.com/apple/swift/issues/47003
// '#if' in top-level code that contains only declarations should not disturb
// forward reference.

typealias A = B

#if false
func foo() {}
#endif

struct B {}

typealias C = D

#if true
print("ok")
#endif

struct D {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/pound-if-top-level-4.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
