// RUN; %target-typecheck-verify-swift -D FOO

var x = 0

#if FOO
x = 1
#else
x = 2
#endif

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/pound-if-top-level-clean.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -D FOO %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
