// RUN; %target-typecheck-verify-swift

// Make sure we can recover by ignoring the '}' in the #if.
struct S {
  func foo() {
#if true
  } // expected_error {{unexpected '}' in conditional compilation block}}
#endif
  }
  func bar() {
#if false
  } // expected_error {{unexpected '}' in conditional compilation block}}
#endif
  }
  func baz() {}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/pound-if-inside-function-5.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-error@7:3 {{}} // unexpected_rbrace_in_conditional_compilation_block
// expected-error@12:3 {{}} // unexpected_rbrace_in_conditional_compilation_block
// ---- end ASTGen parity ----
