// RUN; %swift -typecheck %s -verify -target powerpc64-unknown-linux-gnu -disable-objc-interop -parse-stdlib
// RUN; %swift-ide-test -test-input-complete -source-filename=%s -target powerpc64-unknown-linux-gnu

// expected_warning@<unknown> * {{libc not found for 'powerpc64-unknown-linux-gnu'; C stdlib may be unavailable}}

#if arch(powerpc64) && os(Linux) && _runtime(_Native) && _endian(big) && _pointerBitWidth(_64)
#if _hasAtomicBitWidth(_8) && _hasAtomicBitWidth(_16) && _hasAtomicBitWidth(_32) && _hasAtomicBitWidth(_64)
class C {}
var x = C()
#endif
#endif
var y = x
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/powerpc64LinuxTarget.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -target powerpc64-unknown-linux-gnu -disable-objc-interop -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-warning@<unknown> {{}} // libc_not_found
// ---- end ASTGen parity ----
