// RUN; %target-typecheck-verify-swift -swift-version 4 -D FOO

#if !swift(>=2.2)
// There should be no error here.
foo bar
#else
let _: Int = 1
#endif

#if (swift(>=2.2))
let _: Int = 1
#else
// There should be no error here.
foo bar
#endif

#if swift(>=99.0) || swift(>=88.1.1)
// There should be no error here.
foo bar baz
#else
undefinedElse() // expected_error {{cannot find 'undefinedElse' in scope}}
#endif

#if swift(>=99.0) || FOO
undefinedIf() // expected_error {{cannot find 'undefinedIf' in scope}}
#else
undefinedElse()
#endif

#if swift(>=99.0) && FOO
// There should be no error here.
foo bar baz
#else
undefinedElse() // expected_error {{cannot find 'undefinedElse' in scope}}
#endif

#if FOO && swift(>=2.2)
undefinedIf() // expected_error {{cannot find 'undefinedIf' in scope}}
#else
// There should be no error here.
foo bar baz
#endif

#if swift(>=2.2) && swift(>=1)
undefinedIf() // expected_error {{cannot find 'undefinedIf' in scope}}
#else
// There should be no error here.
foo bar baz
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/sequence_version.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -swift-version 4 -D FOO %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
