// RUN; %target-typecheck-verify-swift -D FOO

// This test is meant to ensure that mixes of top-level declarations, statements
// and expressions within #if blocks parse correctly
var x = 0
#if FOO
class C{}
x = x+1
#endif

#if FOO
x = x+1
class D{}
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/topLevelDeclarations.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -D FOO %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
