// RUN; %swift -typecheck %s -verify -target x86_64-apple-macosx10.9 -parse-stdlib

struct Foo {}

func useFoo(_ foo: Foo) {}

#if arch(x86_64) && os(OSX)
  useFoo(Foo()) // This should not be parsed as a trailing closure
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/trailingClosureOnTargetConfig.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -target x86_64-apple-macosx10.9 -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// ---- end ASTGen parity ----
