// RUN; %swift -typecheck %s -verify -target wasm32-unknown-wasip1-threads -parse-stdlib
// RUN; %swift-ide-test -test-input-complete -source-filename=%s -target wasm32-unknown-wasip1-threads

// expected_warning@<unknown> * {{libc not found for 'wasm32-unknown-wasip1-threads'; C stdlib may be unavailable}}

#if _runtime(_multithreaded)
  func underThreads() {
    foo() // expected_error {{cannot find 'foo' in scope}}
  }
#endif
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/wasm32ThreadsTarget.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -target wasm32-unknown-wasip1-threads -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-warning@<unknown> {{}} // libc_not_found
// ---- end ASTGen parity ----
