// RUN; %swift -typecheck %s -verify -target x86_64-unknown-freebsd10 -disable-objc-interop -parse-stdlib
// RUN; %swift-ide-test -test-input-complete -source-filename=%s -target x86_64-unknown-freebsd10

// expected_warning@<unknown> * {{libc not found for 'x86_64-unknown-freebsd10'; C stdlib may be unavailable}}

#if arch(x86_64) && os(FreeBSD) && _runtime(_Native) && _endian(little) && _pointerBitWidth(_64)
#if _hasAtomicBitWidth(_8) && _hasAtomicBitWidth(_16) && _hasAtomicBitWidth(_32) && _hasAtomicBitWidth(_64) && _hasAtomicBitWidth(_128)
class C {}
var x = C()
#endif
#endif
var y = x
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/ConditionalCompilation/x64FreeBSDTarget.swift
// RUN: %swift -parse -verify -disable-objc-attr-requires-foundation-module -target x86_64-unknown-freebsd10 -disable-objc-interop -parse-stdlib %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// parity: passing
// expected-warning@<unknown> {{}} // libc_not_found
// ---- end ASTGen parity ----
