#!/usr/bin/env python3
"""Generate the ASTGen diagnostic-parity lit suite.

For every frontend configuration of every test in test/Parse, this records the
diagnostics the *legacy* C++ parser emits (the oracle) and writes a lit test
under test/ASTGenParity/Parse that runs the same source through ASTGen
(-enable-experimental-feature ParserASTGen) with -verify, expecting exactly
those diagnostics.  Expectations check location and severity only
(`expected-error@L:C {{}}`); message wording is compared in the report.

Tests where ASTGen is not yet at parity are marked `// XFAIL: *`, so fixing a
gap makes the test XPASS and forces the marker to be removed (a ratchet).

  generate.py plan                          # enumerate configs, write manifest
  generate.py generate --build-dir DIR      # harvest, emit tests, report
  generate.py check --build-dir DIR         # regenerate and diff (drift)
  generate.py check --structural            # bodies still match test/Parse

DIR is a build-script build dir, e.g. ../build/Ninja-RelWithDebInfoAssert.
"""

import argparse
import collections
import csv
import glob
import json
import pathlib
import re
import shlex
import shutil
import subprocess
import sys
import tempfile

SWIFT_SRC = pathlib.Path(__file__).resolve().parents[2]
CORPUS = 'test/Parse'
SUITE = 'test/ASTGenParity'
TOOL_DIR = SWIFT_SRC / 'utils' / 'astgen-parity'

HEADER = (b'// ---- ASTGen parity: generated by '
          b'utils/astgen-parity/generate.py; DO NOT EDIT ----')
PAD = b'// astgen-parity-pad'
STATUS_PENDING = b'// parity: pending'
STATUS_PASSING = b'// parity: passing'
STATUS_XFAIL = b'// XFAIL: *'
# Fixed last line, so diagnostics reported at the end of the final line (e.g.
# unterminated block comments) don't depend on the block's content.
TRAILER = b'// ---- end ASTGen parity ----'
STAGING = 'pending'
# Sub-directory per test: the gap type behind most of its failures.
GAP_TYPES = ['missing', 'extra', 'wrong-column', 'wrong-severity']

# Same-length replacements that make the copied body inert for lit and the
# verifier while keeping every line and column of the original source.
NEUTRALIZE = [
    (b'expected-', b'expected_'),
    (b'RUN:', b'RUN;'),
    (b'REQUIRES:', b'REQUIRES;'),
    (b'UNSUPPORTED:', b'UNSUPPORTED;'),
    (b'XFAIL:', b'XFAIL;'),
    (b'ALLOW_RETRIES:', b'ALLOW_RETRIES;'),
    (b'DEFINE:', b'DEFINE;'),  # also covers REDEFINE:
    (b'END.', b'END,'),
]
EXPANSION_MARKER_RE = re.compile(rb'(//\s*)#(?=[A-Za-z0-9_-]+@\d)')

DRIVERS = {
    '%target-typecheck-verify-swift': '%target-swift-frontend',
    '%target-swift-frontend': '%target-swift-frontend',
    '%swift': '%swift',
}
KEEP_FLAG = {
    '-parse-stdlib', '-parse-as-library', '-disable-objc-interop',
    '-enable-objc-interop', '-disable-implicit-concurrency-module-import',
    '-disable-implicit-string-processing-module-import',
    '-enable-library-evolution', '-playground', '-enable-bare-slash-regex',
    '-enable-experimental-static-assert', '-enable-experimental-move-only',
    '-enable-experimental-concurrency', '-enable-experimental-com-interop',
    '-warnings-as-errors', '-suppress-warnings',
}
KEEP_VALUE = {
    '-swift-version': 1, '-language-mode': 1, '-D': 1, '-target': 1,
    '-module-name': 1, '-enable-experimental-feature': 1,
    '-enable-upcoming-feature': 1, '-disable-experimental-feature': 1,
    '-disable-upcoming-feature': 1, '-module-can-import': 1,
    '-module-can-import-version': 3,
    '-define-enabled-availability-domain': 1,
    '-define-disabled-availability-domain': 1,
    '-define-dynamic-availability-domain': 1, '-define-availability': 1,
}
KEEP_JOINED = {'-strict-concurrency', '-com-interop-model'}
# Actions, verifier knobs, outputs, and import/SDK setup (-parse loads no
# modules).  Body-skipping flags are dropped because the legacy parser never
# parses skipped bodies in -parse mode while ASTGen always does.
DROP_FLAG = {
    '-typecheck', '-parse', '-verify', '-verify-ignore-unrelated',
    '-verify-ignore-unknown', '-verify-ignore-macro-note', '-dump-parse',
    '-dump-ast', '-emit-module', '-c', '-debug-diagnostic-names', '-emit-sil',
    '-emit-silgen', '-emit-ir', '-disable-availability-checking',
    '-enable-source-import', '-experimental-skip-all-function-bodies',
    '-experimental-skip-non-inlinable-function-bodies',
    '-disable-objc-attr-requires-foundation-module',
}
DROP_VALUE = {
    '-I', '-F', '-sdk', '-module-cache-path', '-o', '-emit-module-path',
    '-emit-module-interface-path', '-user-module-version',
    '-import-objc-header', '-serialize-diagnostics-path',
    '-verify-additional-prefix', '-diagnostic-style',
}
DROP_JOINED = {'-diagnostic-style'}
# Changing these would make the comparison meaningless.
PARSER_FEATURES = {'ParserASTGen', 'ParserValidation', 'ParserRoundTrip'}
SKIP_FLAG = {
    '-debugger-support': 'debugger support makes ASTGen fall back to legacy',
}

KIND_ORDER = {'error': 0, 'warning': 1, 'note': 2, 'remark': 3}
DIAG_RE = re.compile(r'^(\S.*?):(\d+):(\d+): error: unexpected '
                     r'(error|warning|note|remark) produced: (.*)$')
UNKNOWN_RE = re.compile(r'^(?:<unknown>:0: )?error: unexpected '
                        r'(error|warning|note|remark) produced: (.*)$')
ELSEWHERE_RE = re.compile(r'diagnostic produced elsewhere|'
                          r'is not parsed for \'expected\' statements')
NAME_RE = re.compile(r'^(.*) \[([A-Za-z0-9_]+)\]$')
CRASH_RE = re.compile(r'Stack dump:|PLEASE submit a bug report')
LIT_STDERR_PREFIX_RE = re.compile(r'^# \| ?')


# ---------------------------------------------------------------------------
# Corpus enumeration
# ---------------------------------------------------------------------------

def known_features():
    text = (SWIFT_SRC / 'include/swift/Basic/Features.def').read_text()
    return set(re.findall(r'^\s*[A-Z_]*FEATURE[A-Z_]*\(\s*(\w+)', text, re.M))


def exceptional_files():
    text = (SWIFT_SRC / 'test/Misc/verify-swift-feature-testing.test-sh'
            ).read_text()
    block = text.split('EXCEPTIONAL_FILES', 1)[1].split(']', 1)[0]
    return set(re.findall(r'pathlib\.Path\("([^"]+)"\)', block))


def run_lines(text):
    runs, cur = [], ''
    for line in text.splitlines():
        m = re.search(r'RUN:(.*)$', line)
        if not m:
            continue
        t = m.group(1).rstrip()
        if t.endswith('\\'):
            cur += t[:-1] + ' '
            continue
        runs.append((cur + t).strip())
        cur = ''
    return runs


def directive_values(text, keyword):
    values = []
    for m in re.finditer(r'\b%s:(.*)$' % keyword, text, re.M):
        values += [v.strip() for v in m.group(1).split(',') if v.strip()]
    return values


def parse_frontend_segment(segment, features):
    """Returns (driver, flags, enabled_features) or a skip-reason string."""
    try:
        toks = shlex.split(segment)
    except ValueError as e:
        return 'unparsable RUN line: %s' % e
    idx = next((i for i, t in enumerate(toks) if t in DRIVERS), None)
    if idx is None:
        return None
    driver = DRIVERS[toks[idx]]
    # %target-typecheck-verify-swift already expands to include %s.
    inputs = 1 if toks[idx] == '%target-typecheck-verify-swift' else 0
    flags, enabled = [], []
    it = iter(toks[idx + 1:])
    for t in it:
        if t in ('>', '2>', '>>', '&>'):
            next(it, None)
            continue
        if t.startswith(('>', '2>', '&>')):
            continue
        if t == '%s':
            inputs += 1
            continue
        if not t.startswith('-'):
            return 'extra input or argument: %s' % t
        name, _, joined = t.partition('=')
        if t in SKIP_FLAG:
            return SKIP_FLAG[t]
        if t in KEEP_FLAG:
            flags.append(t)
        elif t in DROP_FLAG:
            pass
        elif t in KEEP_VALUE:
            vals = [next(it, '') for _ in range(KEEP_VALUE[t])]
            if t.endswith('-feature'):
                feature = vals[0].split(':')[0]
                if feature in PARSER_FEATURES:
                    continue
                if feature not in features:
                    return 'unknown feature: %s' % feature
                if t.startswith('-enable'):
                    enabled.append(feature)
            if any(re.search(r'%t(?![\w-])', v) for v in vals):
                return 'depends on %%t artifacts: %s' % t
            flags.append(t)
            flags += vals
        elif t in DROP_VALUE:
            next(it, None)
        elif t == '-primary-file':
            if next(it, None) == '%s':
                inputs += 1
        elif t.startswith('-D') and len(t) > 2:
            flags.append(t)
        elif joined and name in KEEP_JOINED:
            flags.append(t)
        elif joined and name in DROP_JOINED:
            pass
        else:
            return 'unsupported flag: %s' % t
    if inputs != 1:
        return 'expected exactly one %%s input, got %d' % inputs
    return driver, flags, enabled


def plan():
    """Enumerates configurations. Returns (configs, skips)."""
    features = known_features()
    exceptional = exceptional_files()
    configs, skips = [], []
    for path in sorted((SWIFT_SRC / CORPUS).rglob('*.swift')):
        rel = path.relative_to(SWIFT_SRC).as_posix()
        if 'Inputs' in path.parts:
            continue
        if rel in exceptional:
            skips.append({'source': rel, 'reason': 'feature-checker exception'})
            continue
        if b'\0' in path.read_bytes():
            # git grep treats it as binary, which breaks
            # test/Misc/verify-swift-feature-testing.test-sh.
            skips.append({'source': rel, 'reason': 'contains NUL bytes'})
            continue
        text = path.read_bytes().decode('utf-8', 'replace')
        runs = run_lines(text)
        if any('split-file' in r for r in runs):
            skips.append({'source': rel, 'reason': 'split-file test'})
            continue
        requires = [v for v in directive_values(text, 'REQUIRES')
                    if not v.startswith('swift_feature_')]
        unsupported = directive_values(text, 'UNSUPPORTED')
        seen = []
        for run in runs:
            for segment in re.split(r'\s(?:\|\||\||&&|;)\s', run):
                if '%target-swift-frontend(' in segment:
                    skips.append({'source': rel, 'run': run,
                                  'reason': 'mock-sdk frontend'})
                    continue
                result = parse_frontend_segment(segment, features)
                if result is None:
                    continue
                if isinstance(result, str):
                    skips.append({'source': rel, 'run': run, 'reason': result})
                    continue
                key = (result[0], tuple(result[1]))
                if key not in [(c[0], tuple(c[1])) for c in seen]:
                    seen.append(result)
        if not seen:
            if not any(s['source'] == rel for s in skips):
                skips.append({'source': rel,
                              'reason': 'no frontend RUN line on %s'})
            continue
        for i, (driver, flags, enabled) in enumerate(seen):
            out = rel[len(CORPUS) + 1:]
            if len(seen) > 1:
                out = out[:-len('.swift')] + '.cfg%d.swift' % (i + 1)
            configs.append({
                'source': rel,
                'output': '%s/Parse/%s/%s' % (SUITE, STAGING, out),
                'driver': driver,
                'flags': flags,
                'features': sorted(set(enabled) | {'ParserASTGen'}),
                'requires': sorted(set(requires)),
                'unsupported': sorted(set(unsupported)),
            })
    return configs, skips


# ---------------------------------------------------------------------------
# Test file construction
# ---------------------------------------------------------------------------

def neutralized_body(source):
    body = (SWIFT_SRC / source).read_bytes()
    for old, new in NEUTRALIZE:
        body = body.replace(old, new)
    body = EXPANSION_MARKER_RE.sub(rb'\1_', body)
    if body and not body.endswith(b'\n'):
        body += b'\n'
    return body


def fixed_lines(cfg):
    run = ' '.join([cfg['driver'], '-parse', '-verify',
                    '-disable-objc-attr-requires-foundation-module'] +
                   [shlex.quote(f) if f[:1] != '%' else f
                    for f in cfg['flags']] +
                   ['%s', '-enable-experimental-feature ParserASTGen',
                    '%{astgen-parity-override}'])
    lines = [HEADER, b'// SOURCE; ' + cfg['source'].encode(),
             b'// RUN: ' + run.encode(), b'// REQUIRES: swift_swift_parser']
    lines += [b'// REQUIRES: swift_feature_' + f.encode()
              for f in cfg['features']]
    lines += [b'// REQUIRES: ' + r.encode() for r in cfg['requires']
              if r != 'swift_swift_parser']
    lines += [b'// UNSUPPORTED: ' + u.encode() for u in cfg['unsupported']]
    return lines


def expectation_lines(diags):
    groups = collections.OrderedDict()
    for d in sorted(diags, key=lambda d: (d['line'], d['col'],
                                          KIND_ORDER[d['kind']])):
        groups.setdefault((d['line'], d['col'], d['kind']), []).append(d)
    lines = []
    for (line, col, kind), ds in groups.items():
        loc = '<unknown>' if line == 0 else '%d:%d' % (line, col)
        count = ' %d' % len(ds) if len(ds) > 1 else ''
        ids = ','.join(sorted({d['id'] for d in ds if d['id']}))
        tail = ' // ' + ids if ids else ''
        lines.append(('// expected-%s@%s%s {{}}%s' %
                      (kind, loc, count, tail)).encode())
    return lines


def block_size(cfg, expectations):
    return len(fixed_lines(cfg)) + 1 + len(expectations) + 1


def write_test(cfg, status, size, expectations):
    lines = fixed_lines(cfg) + [status] + expectations
    assert len(lines) + 1 <= size
    lines += [PAD] * (size - len(lines) - 1) + [TRAILER]
    path = SWIFT_SRC / cfg['output']
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(neutralized_body(cfg['source']) +
                     b'\n'.join(lines) + b'\n')


def set_status(cfg, status):
    path = SWIFT_SRC / cfg['output']
    data = path.read_bytes()
    for old in (STATUS_PENDING, STATUS_PASSING, STATUS_XFAIL):
        marker = b'\n' + old + b'\n'
        if marker in data.split(HEADER, 1)[1]:
            head, tail = data.split(HEADER, 1)
            data = head + HEADER + tail.replace(marker,
                                                b'\n' + status + b'\n', 1)
            break
    path.write_bytes(data)


# ---------------------------------------------------------------------------
# lit driving and harvesting
# ---------------------------------------------------------------------------

def lit_command(build_dir):
    lit = SWIFT_SRC.parent / 'llvm-project/llvm/utils/lit/lit.py'
    sites = sorted(glob.glob(str(pathlib.Path(build_dir) /
                                 'swift-macosx-*/test-macosx-*/lit.site.cfg')))
    if not sites:
        sys.exit('no swift test lit.site.cfg under %s' % build_dir)
    return [sys.executable, str(lit), '--param',
            'swift_site_config=%s' % sites[0]]


def run_lit(args, mode, outputs):
    """Runs lit over the given tests; returns {output path: (code, text)}."""
    if not outputs:
        return {}
    with tempfile.TemporaryDirectory() as tmp:
        result = pathlib.Path(tmp) / 'lit.json'
        cmd = lit_command(args.build_dir) + [
            '-j', str(args.jobs), '-q', '--param',
            'astgen_parity_mode=%s' % mode, '--param', 'output_limit=%d' % 2**30,
            '-o', str(result)] + [str(SWIFT_SRC / o) for o in outputs]
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        if not result.exists():
            sys.exit('lit produced no results for mode %r' % mode)
        tests = json.loads(result.read_text())['tests']
    by_output = {}
    for t in tests:
        rel = 'test/' + t['name'].split(' :: ', 1)[1]
        by_output[rel] = (t['code'], t.get('output', ''))
    return by_output


def harvest(cfg, code, text):
    """Returns (diags, error) parsed from a verifier run with no expectations."""
    if code in ('UNSUPPORTED', 'UNRESOLVED'):
        return None, 'lit %s' % code
    if CRASH_RE.search(text):
        return None, 'crash'
    if 'data was truncated' in text:
        return None, 'lit output truncated'
    if ELSEWHERE_RE.search(text):
        return None, 'diagnostic in another buffer'
    target = str(SWIFT_SRC / cfg['output'])
    diags = []
    for line in text.splitlines():
        line = LIT_STDERR_PREFIX_RE.sub('', line)
        m = DIAG_RE.match(line)
        if m:
            if m.group(1) != target:
                return None, 'diagnostic in another file: %s' % m.group(1)
            loc = (int(m.group(2)), int(m.group(3)))
            kind, msg = m.group(4), m.group(5)
        else:
            m = UNKNOWN_RE.match(line)
            if not m:
                continue
            loc, kind, msg = (0, 0), m.group(1), m.group(2)
        n = NAME_RE.match(msg)
        msg, diag_id = (n.group(1), n.group(2)) if n else (msg, '')
        diags.append({'line': loc[0], 'col': loc[1], 'kind': kind,
                      'message': msg, 'id': diag_id})
    if code == 'FAIL' and not diags:
        return None, 'failed without verifier output'
    return diags, None


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

def generate(args):
    configs, skips = plan()
    if args.filter:
        configs = [c for c in configs if args.filter in c['source']]
    suite_dir = SWIFT_SRC / SUITE / 'Parse'
    if suite_dir.exists() and not args.filter:
        shutil.rmtree(suite_dir)

    # Harvest the legacy oracle; repeat until the appended block has exactly
    # as many lines as the skeleton's padding, so EOF diagnostics are stable.
    size = {c['output']: block_size(c, []) for c in configs}
    legacy, pending = {}, list(configs)
    for _ in range(4):
        if not pending:
            break
        for c in pending:
            write_test(c, STATUS_PENDING, size[c['output']], [])
        results = run_lit(args, 'harvest-legacy', [c['output'] for c in pending])
        still = []
        for c in pending:
            diags, err = harvest(c, *results.get(c['output'], ('MISSING', '')))
            if err:
                skips.append({'source': c['source'], 'output': c['output'],
                              'reason': 'legacy harvest: ' + err})
                continue
            want = block_size(c, expectation_lines(diags))
            if want == size[c['output']]:
                legacy[c['output']] = diags
            else:
                size[c['output']] = want
                still.append(c)
        pending = still
    for c in pending:
        skips.append({'source': c['source'], 'output': c['output'],
                      'reason': 'oracle unstable'})
    configs = [c for c in configs if c['output'] in legacy]
    for c in pending + [s for s in skips if 'output' in s]:
        out = c['output']
        if out not in legacy and (SWIFT_SRC / out).exists():
            (SWIFT_SRC / out).unlink()

    # ASTGen diagnostics at the same layout, for the report.
    results = run_lit(args, 'harvest-new', [c['output'] for c in configs])
    new = {}
    for c in configs:
        diags, err = harvest(c, *results.get(c['output'], ('MISSING', '')))
        new[c['output']] = diags if diags is not None else []
        c['new_harvest_error'] = err or ''

    for c in configs:
        write_test(c, STATUS_PENDING, size[c['output']],
                   expectation_lines(legacy[c['output']]))

    # The expectations must encode the legacy parser exactly.
    results = run_lit(args, 'legacy', [c['output'] for c in configs])
    bad = [c for c in configs if results.get(c['output'], ('',))[0] != 'PASS']
    for c in bad:
        skips.append({'source': c['source'], 'output': c['output'],
                      'reason': 'legacy self-check: %s' %
                      results.get(c['output'], ('MISSING',))[0]})
        (SWIFT_SRC / c['output']).unlink()
    configs = [c for c in configs if c not in bad]

    results = run_lit(args, '', [c['output'] for c in configs])
    for c in configs:
        code = results.get(c['output'], ('MISSING',))[0]
        c['status'] = {'PASS': 'passing', 'FAIL': 'xfail'}.get(code, code)
        set_status(c, STATUS_XFAIL if code == 'FAIL' else STATUS_PASSING)

    staging = '%s/Parse/%s/' % (SUITE, STAGING)
    for c in configs:
        old = c['output']
        c['category'] = gap_category(c, legacy[old], new[old])
        rel = old[len(staging):]
        for stale in glob.glob(str(SWIFT_SRC / SUITE / 'Parse' / '*' / rel)):
            if not stale.startswith(str(SWIFT_SRC / staging)):
                pathlib.Path(stale).unlink()
        c['output'] = '%s/Parse/%s/%s' % (SUITE, c['category'], rel)
        dest = SWIFT_SRC / c['output']
        dest.parent.mkdir(parents=True, exist_ok=True)
        (SWIFT_SRC / old).rename(dest)
        legacy[c['output']], new[c['output']] = legacy.pop(old), new.pop(old)
    shutil.rmtree(SWIFT_SRC / staging, ignore_errors=True)

    results = run_lit(args, '', [c['output'] for c in configs])
    codes = collections.Counter(results.get(c['output'], ('MISSING',))[0]
                                for c in configs)

    manifest = {'configs': configs, 'skipped': skips}
    (TOOL_DIR / 'manifest.json').write_text(
        json.dumps(manifest, indent=1, sort_keys=True) + '\n')
    write_report(args.report_dir, configs, skips, legacy, new)
    print('confirm run:', dict(codes))
    print('generated %d tests (%d xfail, %d passing), skipped %d' % (
        len(configs), sum(c['status'] == 'xfail' for c in configs),
        sum(c['status'] == 'passing' for c in configs), len(skips)))
    print('by category:', dict(collections.Counter(
        c['category'] for c in configs).most_common()))
    return codes


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def ifconfig_lines(source):
    """Returns (lines inside #if clauses, #if/#elseif/#else/#endif lines)."""
    inside, directives, depth = set(), set(), 0
    for i, line in enumerate((SWIFT_SRC / source).read_bytes().split(b'\n'), 1):
        s = line.lstrip()
        if re.match(rb'#(if|elseif|else|endif)\b', s):
            directives.add(i)
            if s.startswith(b'#if'):
                depth += 1
            elif s.startswith(b'#endif'):
                depth = max(0, depth - 1)
        elif depth:
            inside.add(i)
    return inside, directives


def line_info(source):
    inside, directives = ifconfig_lines(source)
    return inside, directives, neutralized_body(source).count(b'\n')


def diag_tags(d, inside, directives, body_lines):
    tags = []
    if d['line'] == 0:
        tags.append('unknown_loc')
    elif d['line'] > body_lines:
        tags.append('at_eof')
    if d['line'] in inside:
        tags.append('in_ifconfig_clause')
    if d['line'] in directives:
        tags.append('ifconfig_condition')
    return tags


def gap_category(cfg, legacy, new):
    """passing, crash, ifconfig, a GAP_TYPES entry, or mixed.

    Tests where ASTGen crashes are filed under 'crash'. Otherwise a failing
    test is filed under the gap type behind more than half of its failing
    diagnostics; gaps on or inside #if lines count as 'ifconfig'.
    """
    if cfg['status'] == 'passing':
        return 'passing'
    if cfg['new_harvest_error'] == 'crash':
        return 'crash'
    inside, directives, body_lines = line_info(cfg['source'])
    counts = collections.Counter()
    for cat, l, n in classify(legacy, new):
        if cat not in GAP_TYPES:
            continue
        tags = diag_tags(l or n, inside, directives, body_lines)
        ifconfig = {'in_ifconfig_clause', 'ifconfig_condition'} & set(tags)
        counts['ifconfig' if ifconfig else cat] += 1
    if counts:
        top, n = counts.most_common(1)[0]
        if 2 * n > sum(counts.values()):
            return top
    return 'mixed'


def classify(legacy, new):
    """Pairs diagnostics; returns list of (category, legacy_diag, new_diag)."""
    rows, lrest, nrest = [], list(legacy), list(new)
    passes = [
        ('exact', lambda d: (d['line'], d['col'], d['kind'])),
        ('wrong-column', lambda d: (d['line'], d['kind'])),
        ('wrong-severity', lambda d: (d['line'], d['col'])),
    ]
    for name, key in passes:
        pool = collections.defaultdict(list)
        for d in nrest:
            pool[key(d)].append(d)
        unmatched = []
        for d in lrest:
            if not pool[key(d)]:
                unmatched.append(d)
                continue
            n = pool[key(d)].pop(0)
            nrest.remove(n)
            if name == 'exact':
                name_ = 'matched' if d['message'] == n['message'] \
                    else 'message-differs'
                rows.append((name_, d, n))
            else:
                rows.append((name, d, n))
        lrest = unmatched
    rows += [('missing', d, None) for d in lrest]
    rows += [('extra', None, n) for n in nrest]
    return rows


def write_report(report_dir, configs, skips, legacy, new):
    out = pathlib.Path(report_dir)
    out.mkdir(parents=True, exist_ok=True)
    totals, missing_ids = collections.Counter(), collections.Counter()
    tag_totals = collections.Counter()
    with open(out / 'per-diag.csv', 'w', newline='') as f, \
            open(out / 'per-file.csv', 'w', newline='') as g:
        dw, fw = csv.writer(f), csv.writer(g)
        dw.writerow(['output', 'category', 'line', 'col', 'legacy_kind',
                     'legacy_id', 'legacy_message', 'new_kind', 'new_message',
                     'tags'])
        cats = ['matched', 'message-differs', 'wrong-column',
                'wrong-severity', 'missing', 'extra']
        fw.writerow(['output', 'status', 'category'] + cats +
                    ['new_harvest_error'])
        for c in configs:
            inside, directives, body_lines = line_info(c['source'])
            per = collections.Counter()
            for cat, l, n in classify(legacy[c['output']], new[c['output']]):
                d = l or n
                tags = diag_tags(d, inside, directives, body_lines)
                per[cat] += 1
                totals[cat] += 1
                if cat != 'matched':
                    tag_totals.update(tags)
                if cat == 'missing':
                    missing_ids[l['id'] or '?'] += 1
                dw.writerow([c['output'], cat, d['line'], d['col'],
                             l and l['kind'], l and l['id'],
                             l and l['message'], n and n['kind'],
                             n and n['message'], ' '.join(tags)])
            fw.writerow([c['output'], c['status'], c['category']] +
                        [per[k] for k in cats] +
                        [c['new_harvest_error']])

    status = collections.Counter(c['status'] for c in configs)
    reasons = collections.Counter(re.sub(r':.*', '', s['reason'])
                                  for s in skips)
    md = ['# ASTGen diagnostic parity: %s' % CORPUS, '',
          '| | count |', '|---|---|',
          '| generated tests | %d |' % len(configs),
          '| xfail (not at parity) | %d |' % status['xfail'],
          '| passing (regression guards) | %d |' % status['passing'],
          '| skipped configs/files | %d |' % len(skips), '',
          '## Tests by directory (gap type behind most failures)', '',
          '| directory | tests |', '|---|---|'] + [
          '| %s/ | %d |' % kv for kv in collections.Counter(
              c['category'] for c in configs).most_common()] + ['',
          '## Diagnostics by category', '', '| category | count |',
          '|---|---|']
    md += ['| %s | %d |' % kv for kv in sorted(totals.items())]
    md += ['', '## Tags on non-matched diagnostics', '', '| tag | count |',
           '|---|---|']
    md += ['| %s | %d |' % kv for kv in tag_totals.most_common()]
    md += ['', '## Top missing legacy diagnostics', '', '| id | count |',
           '|---|---|']
    md += ['| %s | %d |' % kv for kv in missing_ids.most_common(30)]
    md += ['', '## Skip reasons', '', '| reason | count |', '|---|---|']
    md += ['| %s | %d |' % kv for kv in reasons.most_common()]
    (out / 'SUMMARY.md').write_text('\n'.join(md) + '\n')


# ---------------------------------------------------------------------------
# Drift checks
# ---------------------------------------------------------------------------

def check_structural():
    manifest = json.loads((TOOL_DIR / 'manifest.json').read_text())
    bad = 0
    for c in manifest['configs']:
        data = (SWIFT_SRC / c['output']).read_bytes()
        body = data.split(HEADER + b'\n', 1)[0]
        if body != neutralized_body(c['source']):
            print('body drift: %s (from %s)' % (c['output'], c['source']))
            bad += 1
    return bad


def check_full(args):
    suite_dir = SWIFT_SRC / SUITE / 'Parse'
    with tempfile.TemporaryDirectory() as tmp:
        saved = pathlib.Path(tmp) / 'Parse'
        shutil.copytree(suite_dir, saved)
        shutil.copy(TOOL_DIR / 'manifest.json', pathlib.Path(tmp) / 'm.json')
        args.filter, args.report_dir = None, str(pathlib.Path(tmp) / 'report')
        generate(args)
        diff = subprocess.run(['diff', '-r', '-q', str(saved), str(suite_dir)],
                              capture_output=True, text=True).stdout
        shutil.rmtree(suite_dir)
        shutil.copytree(saved, suite_dir)
        shutil.copy(pathlib.Path(tmp) / 'm.json', TOOL_DIR / 'manifest.json')
    print(diff or 'no drift')
    return 1 if diff else 0


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawTextHelpFormatter)
    sub = p.add_subparsers(dest='cmd', required=True)
    sub.add_parser('plan')
    for name in ('generate', 'check'):
        s = sub.add_parser(name)
        s.add_argument('--build-dir')
        s.add_argument('--jobs', type=int, default=8)
        s.add_argument('--report-dir', default=str(TOOL_DIR / 'report'))
        if name == 'generate':
            s.add_argument('--filter', help='only sources containing this')
        else:
            s.add_argument('--structural', action='store_true')
    args = p.parse_args()

    if args.cmd == 'plan':
        configs, skips = plan()
        reasons = collections.Counter(re.sub(r':.*', '', s['reason'])
                                      for s in skips)
        print('%d configs from %d files; %d skips' % (
            len(configs), len({c['source'] for c in configs}), len(skips)))
        for r, n in reasons.most_common():
            print('  %4d  %s' % (n, r))
        return 0
    if args.cmd == 'check' and args.structural:
        return 1 if check_structural() else 0
    if not args.build_dir:
        p.error('--build-dir is required')
    if args.cmd == 'generate':
        codes = generate(args)
        return 0 if set(codes) <= {'PASS', 'XFAIL'} else 1
    return check_full(args)


if __name__ == '__main__':
    sys.exit(main())
