// RUN; %target-typecheck-verify-swift  -target %target-swift-5.1-abi-triple

// REQUIRES; concurrency

// Parsing function declarations with 'async'
func asyncGlobal1() async { }
func asyncGlobal2() async throws { }

func asyncGlobal3() throws async { } // expected_error{{'async' must precede 'throws'}}{{28-34=}}{{21-21=async }}

func asyncGlobal3(fn: () throws -> Int) rethrows async { } // expected_error{{'async' must precede 'rethrows'}}{{50-56=}}{{41-41=async }}

func asyncGlobal4() -> Int async { } // expected_error{{'async' may only occur before '->'}}{{28-34=}}{{21-21=async }}

func asyncGlobal5() -> Int async throws { }
// expected_error@-1{{'async' may only occur before '->'}}{{28-34=}}{{21-21=async }}
// expected_error@-2{{'throws' may only occur before '->'}}{{34-41=}}{{21-21=throws }}

func asyncGlobal6() -> Int throws async { }
// expected_error@-1{{'throws' may only occur before '->'}}{{28-35=}}{{21-21=throws }}
// expected_error@-2{{'async' may only occur before '->'}}{{35-41=}}{{21-21=async }}

func asyncGlobal7() throws -> Int async { } // expected_error{{'async' may only occur before '->'}}{{35-41=}}{{21-21=async }}

func asyncGlobal8() async throws async -> async Int async {}
// expected_error@-1{{'async' has already been specified}} {{34-40=}}
// expected_error@-2{{'async' has already been specified}} {{43-49=}}
// expected_error@-3{{'async' has already been specified}} {{53-59=}}

class X {
  init() async { }

  deinit async { } // expected_error{{deinitializers cannot have a name}}

  func f() async { }

  subscript(x: Int) async -> Int { // expected_error{{expected '->' for subscript element type}}
    // expected_error@-1{{single argument function types require parentheses}}
    // expected_error@-2{{cannot find type 'async' in scope}}
    // expected_note@-3{{cannot use module 'async' as a type}}
    get {
      return 0
    }

    set async { // expected_error{{'set' accessor cannot have specifier 'async'}}
    }
  }
}

// Parsing function types with 'async'.
typealias AsyncFunc1 = () async -> ()
typealias AsyncFunc2 = () async throws -> ()
typealias AsyncFunc3 = () throws async -> () // expected_error{{'async' must precede 'throws'}}{{34-40=}}{{27-27=async }}

// Parsing type expressions with 'async'.
func testTypeExprs() {
  let _ = [() async -> ()]()
  let _ = [() async throws -> ()]()
  let _ = [() throws async -> ()]()  // expected_error{{'async' must precede 'throws'}}{{22-28=}}{{15-15=async }}

  let _ = [() -> async ()]() // expected_error{{'async' may only occur before '->'}}{{18-24=}}{{15-15=async }}
}

// Parsing await syntax.
struct MyFuture {
  func await() -> Int { 0 }
}

func testAwaitExpr() async {
  let _ = await asyncGlobal1()
  let myFuture = MyFuture()
  let _ = myFuture.await()
}

func getIntSomeday() async -> Int { 5 }

func testAsyncLet() async {
  async let x = await getIntSomeday()
  _ = await x
}

async func asyncIncorrectly() { } // expected_error{{'async' must be written after the parameter list of a function}}{{1-7=}}{{30-30= async}}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/async.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -target %target-swift-5.1-abi-triple %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: concurrency
// XFAIL: *
// expected-error@9:28 {{}} // async_after_throws
// expected-error@11:50 {{}} // async_after_throws
// expected-error@13:28 {{}} // async_or_throws_in_wrong_position
// expected-error@15:28 {{}} // async_or_throws_in_wrong_position
// expected-error@15:34 {{}} // async_or_throws_in_wrong_position
// expected-error@19:28 {{}} // async_or_throws_in_wrong_position
// expected-error@19:35 {{}} // async_or_throws_in_wrong_position
// expected-error@23:35 {{}} // async_or_throws_in_wrong_position
// expected-error@25:34 {{}} // duplicate_effects_specifier
// expected-error@25:43 {{}} // duplicate_effects_specifier
// expected-error@25:53 {{}} // duplicate_effects_specifier
// expected-error@33:10 {{}} // destructor_has_name
// expected-error@37:21 2 {{}} // expected_arrow_subscript,function_type_no_parens
// expected-error@45:9 {{}} // invalid_accessor_specifier
// expected-error@53:34 {{}} // async_after_throws
// expected-error@59:22 {{}} // async_after_throws
// expected-error@61:18 {{}} // async_or_throws_in_wrong_position
// expected-error@82:1 {{}} // async_func_modifier
// ---- end ASTGen parity ----
