// RUN; %target-typecheck-verify-swift -enable-experimental-feature CoroutineAccessors

// REQUIRES; swift_feature_CoroutineAccessors

class Klass {}

struct Wrapper {
  let _k: Klass
  var _otherK: Klass

  var k1: Klass {
    borrow {
      return _k 
    }
  }
  var k2: Klass {
    borrow { // expected_error{{variable cannot provide both a 'borrow' accessor and a getter}}
      return _k
    }
    get { // expected_note{{getter defined here}}
      return _k
    }
  }
  var k3: Klass {
    borrow { // expected_error{{variable cannot provide both a 'borrow' accessor and a '_read' accessor}}
      return _k
    }
    _read { // expected_note{{'_read' accessor defined here}}
      yield _k
    }
  }
  var k4: Klass {
    borrow { // expected_error{{variable cannot provide both a 'borrow' accessor and a 'yielding borrow' accessor}}
      return _k
    }
    // expected_warning@+1{{'read' is deprecated; please use 'yielding borrow' instead}}
    read { // expected_note{{'yielding borrow' accessor defined here}}
      yield _k
    }
  }
  var k5: Klass {
    mutate { // expected_error{{variable with a 'mutate' accessor must also have a 'borrow' accessor}}
      return &_otherK
    }
  }
  var k6: Klass {
    borrow { // expected_error{{A 'borrow' accessor can only be defined along with a 'mutate' accessor}}
      return _otherK
    }
    mutate { // expected_error{{variable cannot provide both a 'mutate' accessor and a setter}}
      return &_otherK
    }
    _modify {
      yield &_otherK
    }
    set { // expected_note{{setter defined here}}
      _otherK = newValue
    }
  }
  var k7: Klass {
    borrow { // expected_error{{A 'borrow' accessor can only be defined along with a 'mutate' accessor}}
      return _otherK
    }
    mutate { // expected_note{{mutate accessor defined here}}
      return &_otherK
    }
    unsafeMutableAddress { // expected_error{{variable cannot provide both a mutable addressor and a 'mutate' accessor}}
    }
  }
  var k8: Klass {
    borrow async throws { // expected_error{{'borrow' accessor cannot have specifier 'async'}} expected_error{{'borrow' accessor cannot have specifier 'throws'}}
      return _otherK
    }
    mutate async throws { // expected_error{{'mutate' accessor cannot have specifier 'async'}} expected_error{{'mutate' accessor cannot have specifier 'throws'}}
      return &_otherK
    }
  }
  var k9: Klass {
    borrow { // expected_error{{A 'borrow' accessor can only be defined along with a 'mutate' accessor}}
      return _otherK
    }
    _modify {
      yield &_otherK
    }
  }
  var k10: Klass {
    borrow { // expected_error{{A 'borrow' accessor can only be defined along with a 'mutate' accessor}}
      return _otherK
    }
    yielding mutate {
      yield &_otherK
    }
  }
  var k11: Klass {
    borrow { // expected_error{{A 'borrow' accessor can only be defined along with a 'mutate' accessor}}
      return _otherK
    }
    set {
      _otherK = newValue
    }
  }
  var k12: Klass {
    get {
      return _otherK
    }
    mutate { // expected_error{{A 'mutate' accessor can only be defined along with a 'borrow' accessor}}
      return &_otherK
    }
  }
}

var i: Int

var i_accessor: Int {
  borrow { // expected_error{{a 'borrow' accessor is unsupported here}}
    fatalError()
  }
  mutate { // expected_error{{a 'mutate' accessor is unsupported here}}
    return &i // expected_error{{'&' may only be used to pass an argument to inout parameter}}
  }
}

// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/borrow_and_mutate_accessors.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-feature CoroutineAccessors %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_CoroutineAccessors
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@17:5 {{}} // conflicting_accessor
// expected-note@20:5 {{}} // previous_accessor
// expected-error@25:5 {{}} // conflicting_accessor
// expected-note@28:5 {{}} // previous_accessor
// expected-error@33:5 {{}} // conflicting_accessor
// expected-warning@37:5 {{}} // old_coroutine_accessor
// expected-note@37:5 {{}} // previous_accessor
// expected-error@42:5 {{}} // missing_borrow_accessor
// expected-error@47:5 {{}} // borrow_mutate_pair_restrict
// expected-error@50:5 {{}} // conflicting_accessor
// expected-note@56:5 {{}} // previous_accessor
// expected-error@61:5 {{}} // borrow_mutate_pair_restrict
// expected-note@64:5 {{}} // previous_accessor
// expected-error@67:5 {{}} // conflicting_accessor
// expected-error@71:12 {{}} // invalid_accessor_specifier
// expected-error@71:18 {{}} // invalid_accessor_specifier
// expected-error@74:12 {{}} // invalid_accessor_specifier
// expected-error@74:18 {{}} // invalid_accessor_specifier
// expected-error@79:5 {{}} // borrow_mutate_pair_restrict
// expected-error@87:5 {{}} // borrow_mutate_pair_restrict
// expected-error@95:5 {{}} // borrow_mutate_pair_restrict
// expected-error@106:5 {{}} // borrow_mutate_pair_restrict
// expected-error@115:10 {{}} // borrow_mutate_accessor_not_supported_in_decl
// expected-error@118:10 {{}} // borrow_mutate_accessor_not_supported_in_decl
// ---- end ASTGen parity ----
