// RUN; %target-typecheck-verify-swift

@diagnose(DeprecatedDeclaration, as: error)
func foo() {}

@diagnose(Deprecate, as: warning) // expected_warning {{the diagnostic group identifier 'Deprecate' is unknown}}
func bar() {}

@diagnose(DeprecatedDeclaration, as: what) // expected_error {{expected diagnostic behavior argument 'what' to be either 'error', 'warning' or 'ignored'}}
func baz() {}

// expected_warning @+1 {{the diagnostic group identifier 'Hmm' is unknown}}
@diagnose(Hmm, as: what) // expected_error {{expected diagnostic behavior argument 'what' to be either 'error', 'warning' or 'ignored'}}
func qux() {}

@diagnose(ExistentialAny, as: ignored, reason: "for a lit test")
func quux() {}

@diagnose(ExistentialAny, as: ignored, reason: BadReason) // expected_error {{expected string literal in 'diagnose' attribute}}
func corge() {}

// Backward compatibility: @warn is an alias for @diagnose
@warn(DeprecatedDeclaration, as: error) // expected_warning {{'@warn' has been renamed to '@diagnose'}}
func warnAlias() {}

@warn(ExistentialAny, as: ignored, reason: "backward compat test") // expected_warning {{'@warn' has been renamed to '@diagnose'}}
func warnAliasWithReason() {}

@warn(ExistentialAny, as: ignored, reason: BadReason) // expected_warning {{'@warn' has been renamed to '@diagnose'}} expected_error {{expected string literal in 'warn' attribute}}
func warnAliasCorge() {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnose_attribute.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-warning@6:2 {{}} // attr_diagnose_unknown_diagnostic_group_identifier
// expected-error@9:2 {{}} // attr_diagnose_expected_known_behavior
// expected-error@13:2 {{}} // attr_diagnose_expected_known_behavior
// expected-warning@13:2 {{}} // attr_diagnose_unknown_diagnostic_group_identifier
// expected-error@19:2 {{}} // attr_expected_string_literal
// expected-warning@23:2 {{}} // attr_renamed_warning
// expected-warning@26:2 {{}} // attr_renamed_warning
// expected-error@29:2 {{}} // attr_expected_string_literal
// expected-warning@29:2 {{}} // attr_renamed_warning
// ---- end ASTGen parity ----
