// RUN; %target-typecheck-verify-swift 

// https://github.com/apple/swift/issues/46814
// Misleading/wrong error message for malformed '@available'

@available(OSX 10.6, *) // no error
func availableSince10_6() {}

@available(OSX, introduced: 10.0, deprecated: 10.12) // no error
func introducedFollowedByDeprecated() {}

@available(OSX 10.0, deprecated: 10.12)
// expected_error@-1 {{'deprecated' can't be combined with shorthand specification 'OSX 10.0'}}
// expected_note@-2 {{did you mean to specify an introduction version?}} {{15-15=, introduced:}}
// expected_error@-3 {{expected declaration}}
func shorthandFollowedByDeprecated() {}

@available(OSX 10.0, introduced: 10.12)
// expected_error@-1 {{'introduced' can't be combined with shorthand specification 'OSX 10.0'}}
// expected_error@-2 {{expected declaration}}
func shorthandFollowedByIntroduced() {}

@available(iOS 6.0, OSX 10.8, *) // no error
func availableOnMultiplePlatforms() {}

@available(iOS 6.0, OSX 10.0, deprecated: 10.12)
// expected_error@-1 {{'deprecated' can't be combined with shorthand specification 'OSX 10.0'}}
// expected_error@-2 {{expected declaration}}
func twoShorthandsFollowedByDeprecated() {}


// https://github.com/apple/swift/issues/51114
// Missing/wrong warning message for '*' or 'swift' platform.

@available(*, deprecated: 4.2)
// expected_warning@-1 {{unexpected version number for *}}
func allPlatformsDeprecatedVersion() {}

@available(*, deprecated, obsoleted: 4.2)
// expected_warning@-1 {{unexpected version number for *}}
func allPlatformsDeprecatedAndObsoleted() {}

@available(*, introduced: 4.0, deprecated: 4.1, obsoleted: 4.2)
// expected_warning@-1 {{unexpected version number for *}}
func allPlatformsDeprecatedAndObsoleted2() {}

@available(swift, unavailable)
// expected_warning@-1 {{'unavailable' cannot be used in '@available' attribute for Swift}}
func swiftUnavailable() {}

@available(swift, unavailable, introduced: 4.2)
// expected_warning@-1 {{'unavailable' cannot be used in '@available' attribute for Swift}}
func swiftUnavailableIntroduced() {}

@available(swift, deprecated)
// expected_warning@-1 {{expected version number with 'deprecated' in '@available' attribute for Swift}}
func swiftDeprecated() {}

@available(swift, deprecated, obsoleted: 4.2)
// expected_warning@-1 {{expected version number with 'deprecated' in '@available' attribute for Swift}}
func swiftDeprecatedObsoleted() {}

@available(swift, message: "missing valid option")
// expected_warning@-1 {{expected 'introduced', 'deprecated', or 'obsoleted' in '@available' attribute for Swift}}
func swiftMessage() {}

@available(swift 5, deprecated: 6)
// expected_error@-1 {{'deprecated' can't be combined with shorthand specification 'swift 5'}}
// expected_note@-2 {{did you mean to specify an introduction version?}} {{17-17=, introduced:}}
// expected_error@-3 {{expected declaration}}
func swiftShorthandFollowedByDeprecated() {}

@available(*, unavailable, message: "\("message")")
// expected_error@-1{{'message' cannot be an interpolated string literal}}
func interpolatedMessage() {}

@available(*, unavailable, message: """
  foobar message.
  """)
func multilineMessage() {}
multilineMessage()
// expected_error@-1{{'multilineMessage()' is unavailable: foobar message.}}
// expected_note@-6{{'multilineMessage()' has been explicitly marked unavailable here}}

@available(*, unavailable, message: " ")
func emptyMessage() {}
emptyMessage()
// expected_error@-1{{'emptyMessage()' is unavailable:  }}
// expected_note@-4{{'emptyMessage()' has been explicitly marked unavailable here}}

// expected_error@+1{{'message' cannot be an extended escaping string literal}}
@available(*, unavailable, message: #"""
  foobar message.
  """#)
func extendedEscapedMultilineMessage() {}

// expected_error@+1{{'renamed' cannot be an extended escaping string literal}}
@available(*, unavailable, renamed: #"available()"#)
func extendedEscapedRenamed() {}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/diagnose_availability.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-note@12:12 {{}} // avail_query_meant_introduced
// expected-error@12:22 {{}} // avail_query_argument_and_shorthand_mix_not_allowed
// expected-error@12:32 {{}} // expected_decl
// expected-error@18:22 {{}} // avail_query_argument_and_shorthand_mix_not_allowed
// expected-error@18:32 {{}} // expected_decl
// expected-error@26:31 {{}} // avail_query_argument_and_shorthand_mix_not_allowed
// expected-error@26:41 {{}} // expected_decl
// expected-note@67:12 {{}} // avail_query_meant_introduced
// expected-error@67:21 {{}} // avail_query_argument_and_shorthand_mix_not_allowed
// expected-error@67:31 {{}} // expected_decl
// expected-error@73:2 {{}} // forbidden_interpolated_string
// expected-error@92:2 {{}} // forbidden_extended_escaping_string
// expected-error@98:2 {{}} // forbidden_extended_escaping_string
// ---- end ASTGen parity ----
