// RUN; %target-typecheck-verify-swift -target %target-swift-5.1-abi-triple

// REQUIRES; concurrency

typealias F = @concurrent () async -> Void

typealias E = @concurrent () -> Void
// expected_error@-1 {{cannot use '@concurrent' on non-async function type}}

func test1(_: nonisolated(nonsending) (Int...) async -> Void) {}
func test2(_: @concurrent (Int...) async -> Void) {}

func test_err1_concurrent(_: @concurrent @MainActor () async -> Void) {}
// expected_error@-1 {{cannot use '@concurrent' because function type is isolated to a global actor 'MainActor'}}

func test_err1_caller(_: nonisolated(nonsending) @MainActor () async -> Void) {}
// expected_error@-1 {{cannot use 'nonisolated(nonsending)' because function type is isolated to a global actor 'MainActor'}}

func test_err2_concurrent(_: @concurrent @isolated(any) () async -> Void) {}
// expected_error@-1 {{cannot use '@concurrent' together with '@isolated(any)'}}

func test_err2_caller(_: nonisolated(nonsending) @isolated(any) () async -> Void) {}
// expected_error@-1 {{cannot use 'nonisolated(nonsending)' together with '@isolated(any)'}}

func test_err3_concurrent(_: @concurrent (isolated (any Actor)?) async -> Void) {}
// expected_error@-1 {{cannot use '@concurrent' together with an isolated parameter}}

func test_err3_caller(_: nonisolated(nonsending) (isolated (any Actor)?) async -> Void) {}
// expected_error@-1 {{cannot use 'nonisolated(nonsending)' together with an isolated parameter}}

func test_err4(_: nonisolated (Int) -> Void) {}
// expected_error@-1 {{expected 'nonsending' in modifier}}
// expected_error@-2 {{expected '{' in body of function declaration}}
// expected_warning@-3 {{extraneous whitespace between attribute name and '('; this is an error in the Swift 6 language mode}}
// expected_error@-4 {{consecutive statements on a line must be separated by ';'}}
// expected_error@-5 {{expected expression}}

func test_err5(_: nonisolated( () async -> Void) {}
// expected_error@-1 {{expected 'nonsending' in modifier}}

func test_err6(_: nonisolated(hello) () async -> Void) {}
// expected_error@-1 {{expected 'nonsending' in modifier}}
// expected_error@-2 {{cannot have more than one parameter list}}
// expected_error@-3 {{cannot find type 'hello' in scope}}
// expected_error@-4 {{onsecutive statements on a line must be separated by ';'}}
// expected_error@-5 {{expected expression}}

func test_err7(_: nonisolated(hello () async -> Void) {}
// expected_error@-1 {{expected 'nonsending' in modifier}}
// expected_error@-2 {{cannot find type 'hello' in scope}}

func test_err8(_: @concurrent Int) {} // expected_error {{attribute does not apply to type}}

do {
  let _ = [nonisolated(nonsending) () async -> Void]()
  let _ = [nonisolated(nonsending) () -> Void]()
  // expected_error@-1 {{cannot use 'nonisolated(nonsending)' on non-async function type}}
}

protocol P {}

struct S : nonisolated
             P { // Ok
}

do {
  func nonisolated() {}

  // `nonisolated` is parsed as a function call
  nonisolated // expected_error {{function is unused}}
  (42) // expected_warning {{integer literal is unused}}

  let _: nonisolated // expected_error {{cannot find type 'nonisolated' in scope}}
    (Int) async -> Void // expected_error {{expected member name or initializer call after type name}}
  // expected_note@-1 {{use '.self' to reference the type object}}
  // expected_warning@-2 {{expression of type '((Int) async -> Void).Type' is unused}}

  _ = [nonisolated()]
}

do {
  func nonisolated(_: Int) -> Int { 42 }

  nonisolated(0) // expected_warning {{result of call to 'nonisolated' is unused}}
  print("hello")
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/execution_behavior_attrs.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -target %target-swift-5.1-abi-triple %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// REQUIRES: concurrency
// XFAIL: *
// expected-warning@31:30 {{}} // attr_extra_whitespace_before_lparen
// expected-error@31:32 {{}} // nonisolated_nonsending_incorrect_modifier
// expected-error@31:44 2 {{}} // expected_expr,statement_same_line_without_semi
// expected-error@38:32 {{}} // nonisolated_nonsending_incorrect_modifier
// expected-error@41:15 {{}} // parameter_curry_syntax_removed
// expected-error@41:31 {{}} // nonisolated_nonsending_incorrect_modifier
// expected-error@41:54 2 {{}} // expected_expr,statement_same_line_without_semi
// expected-error@48:31 {{}} // nonisolated_nonsending_incorrect_modifier
// ---- end ASTGen parity ----
