// RUN; %target-typecheck-verify-swift

struct FooStructConstructorA {
  init // expected_error {{expected '('}}
  // expected_error@-1{{initializer requires a body}}
}

struct FooStructConstructorB {
  init() // expected_error {{initializer requires a body}}
}

struct FooStructConstructorC {
  init {} // expected_error {{expected '('}}{{7-7=()}}
  // expected_note@-1{{'init()' previously declared here}}
  init<T> {} // expected_error {{expected '('}} {{10-10=()}}
  // expected_error@-1{{generic parameter 'T' is not used in function signature}}
  init? { self.init() } // expected_error {{expected '('}} {{8-8=()}}
  // expected_error@-1{{invalid redeclaration of 'init()'}}
}

struct FooStructConstructorD {
  init() -> FooStructConstructorD { }
  // expected_error@-1{{initializers cannot have a result type}}
}

struct FooStructDeinitializerA {
  deinit // expected_error {{expected '{' for deinitializer}}
  deinit x // expected_error {{deinitializers cannot have a name}} {{10-12=}}  expected_error {{expected '{' for deinitializer}}
  deinit x() // expected_error {{deinitializers cannot have a name}} {{10-11=}} expected_error {{no parameter clause allowed on deinitializer}} {{11-13=}} expected_error {{expected '{' for deinitializer}}
}

struct FooStructDeinitializerB {
  deinit // expected_error {{expected '{' for deinitializer}}
}

struct FooStructDeinitializerC { // expected_note {{consider adding '~Copyable' to struct 'FooStructDeinitializerC'}}
  deinit {} // expected_error {{deinitializer cannot be declared in struct 'FooStructDeinitializerC' that conforms to 'Copyable'}}
}

class FooClassDeinitializerA {
  deinit(a : Int) {} // expected_error{{no parameter clause allowed on deinitializer}}{{9-18=}}
}

class FooClassDeinitializerB {
  deinit { }
}

class FooClassDeinitializerC {
  deinit x (a : Int) {} // expected_error {{deinitializers cannot have a name}} {{10-12=}} expected_error{{no parameter clause allowed on deinitializer}}{{12-22=}}
}

init {} // expected_error {{initializers may only be declared within a type}} expected_error {{expected '('}} {{5-5=()}}
init() // expected_error {{initializers may only be declared within a type}}
init() {} // expected_error {{initializers may only be declared within a type}}

deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
deinit // expected_error {{expected '{' for deinitializer}}
deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}

struct BarStruct {
  init() {}
  deinit {} // NOTE: this doesn't get diagnosed with the other errors in this file for some reason.
}

extension BarStruct {
  init(x : Int) {}

  // When/if we allow 'var' in extensions, then we should also allow dtors
  deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
}

enum BarUnion {
  init() {}
  deinit {} // NOTE: this doesn't get diagnosed with the other errors in this file for some reason.
}

extension BarUnion {
  init(x : Int) {}
  deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
}

class BarClass {
  init() {}
  deinit {}
}

extension BarClass {
  convenience init(x : Int) { self.init() }
  deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
}

protocol BarProtocol {
  init() {} // expected_error {{protocol initializers must not have bodies}}
  deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
}

extension BarProtocol {
  init(x : Int) {}
  deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
}

func fooFunc() {
  init() {} // expected_error {{initializers may only be declared within a type}}
  deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
}

func barFunc() {
  var x : () = { () -> () in
    // expected_warning@-1 {{variable 'x' was never used; consider replacing with '_' or removing it}}
    init() {} // expected_error {{initializers may only be declared within a type}}
    return
  } ()

  var y : () = { () -> () in
    // expected_warning@-1 {{variable 'y' was never used; consider replacing with '_' or removing it}}
    deinit {} // expected_error {{deinitializers may only be declared within a class, actor, or noncopyable type}}
    return
  } ()
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/init_deinit.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:7 {{}} // expected_lparen_initializer
// expected-error@13:8 {{}} // expected_lparen_initializer
// expected-error@15:11 {{}} // expected_lparen_initializer
// expected-error@17:9 {{}} // expected_lparen_initializer
// expected-error@22:13 {{}} // initializer_result_type
// expected-error@27:9 {{}} // expected_lbrace_destructor
// expected-error@28:10 {{}} // destructor_has_name
// expected-error@28:11 {{}} // expected_lbrace_destructor
// expected-error@29:10 {{}} // destructor_has_name
// expected-error@29:11 {{}} // destructor_params
// expected-error@29:13 {{}} // expected_lbrace_destructor
// expected-error@33:9 {{}} // expected_lbrace_destructor
// expected-error@41:9 {{}} // destructor_params
// expected-error@49:10 {{}} // destructor_has_name
// expected-error@49:12 {{}} // destructor_params
// expected-error@52:6 2 {{}} // expected_lparen_initializer,initializer_decl_wrong_scope
// expected-error@53:5 {{}} // initializer_decl_wrong_scope
// expected-error@54:5 {{}} // initializer_decl_wrong_scope
// expected-error@56:1 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@57:7 {{}} // expected_lbrace_destructor
// expected-error@58:1 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@69:3 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@79:3 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@89:3 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@93:10 {{}} // protocol_init_with_body
// expected-error@94:3 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@99:3 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@103:7 {{}} // initializer_decl_wrong_scope
// expected-error@104:3 {{}} // destructor_decl_outside_class_or_noncopyable
// expected-error@110:9 {{}} // initializer_decl_wrong_scope
// expected-error@116:5 {{}} // destructor_decl_outside_class_or_noncopyable
// ---- end ASTGen parity ----
