// RUN; %target-typecheck-verify-swift

func unbalanced_question(a: Bool, b: Bool, c: Bool, d: Bool) {
  (a ? b) // expected_error{{expected ':' after '? ...' in ternary}}
  (a ? b : c ? d) // expected_error{{expected ':' after '? ...' in ternary}}
  (a ? b ? c : d) // expected_error{{expected ':' after '? ...' in ternary}}
  (a ? b ? c) // expected_error{{expected ':' after '? ...' in ternary}} // expected_error{{expected ':' after '? ...' in ternary}}
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/invalid_ternary_expr.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@4:6 {{}} // expected_colon_after_ternary_question
// expected-error@5:14 {{}} // expected_colon_after_ternary_question
// expected-error@6:6 {{}} // expected_colon_after_ternary_question
// expected-error@7:6 {{}} // expected_colon_after_ternary_question
// expected-error@7:10 {{}} // expected_colon_after_ternary_question
// ---- end ASTGen parity ----
