// RUN; %target-typecheck-verify-swift -enable-experimental-feature Lifetimes

// REQUIRES; swift_feature_Lifetimes

struct E {}

struct NE : ~Escapable {}

@_lifetime(copy ne)
func derive(_ ne: NE) -> NE {
  ne
}

@_lifetime(borrow ne1, copy ne2)
func derive(_ ne1: NE, _ ne2: NE) -> NE {
  if (Int.random(in: 1..<100) < 50) {
    return ne1
  }
  return ne2
}

@_lifetime // expected_error{{expected '(' after lifetime dependence specifier}}
func testMissingLParenError(_ ne: NE) -> NE {
  ne
}

@_lifetime() // expected_error{{expected 'copy', 'borrow', or '&' followed by an identifier or 'self' in lifetime dependence specifier}}
func testMissingDependence(_ ne: NE) -> NE {
  ne
}

@_lifetime(borrow borrow)
func testNameConflict(_ borrow: E) -> NE {
  NE()
}
// ---- ASTGen parity: generated by utils/astgen-parity/generate.py; DO NOT EDIT ----
// SOURCE; test/Parse/lifetime_attr.swift
// RUN: %target-swift-frontend -parse -verify -disable-objc-attr-requires-foundation-module -enable-experimental-feature Lifetimes %s -enable-experimental-feature ParserASTGen %{astgen-parity-override}
// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_Lifetimes
// REQUIRES: swift_feature_ParserASTGen
// XFAIL: *
// expected-error@22:2 {{}} // expected_lparen_after_lifetime_dependence
// expected-error@27:13 {{}} // expected_identifier_or_index_or_self_after_lifetime_dependence
// ---- end ASTGen parity ----
